import {writeFileSync} from 'node:fs';
import { CATALOG_SOURCE } from '../../src/data/catalog-source';
import { applyAlgorithm, canonicalOrientation, invertAlgorithm, isF2LSolved, isOLLOriented, isSolved, solvedCube } from '../../src/domain/cube';
import type { AlgorithmCase } from '../../src/domain/types';
const groups: Record<string,string> = {'Dot':'Ponto','Square Shape':'Quadrado','Small Lightning Bolt':'Raio pequeno','Fish Shape':'Peixe','Knight Move Shape':'Cavalo','Cross':'Cruz','Corners Oriented':'Cantos orientados','Awkward Shape':'Irregulares','P Shape':'Forma P','T Shape':'Forma T','C Shape':'Forma C','W Shape':'Forma W','Big Lightning Bolt':'Raio grande','Small L Shape':'L pequeno','I Shape':'Linha','Edges Only':'Somente arestas','Adjacent Corner Swap':'Cantos adjacentes','Diagonal Corner Swap':'Cantos diagonais'};
const twoLookOLL=new Set(['1','21','22','23','24','25','26','27','44','45']);
const twoLookPLL=new Set(['Aa','E','Ua','Ub','H','Z']);
// Alternatives have separate viewing/AUF conventions in the source. Only include
// alternatives that solve this exact initial state, adjusting U and y explicitly.
function compatibleAlternatives(raw: readonly string[], primary: string, family: 'OLL'|'PLL'): string[] {
  const initial=applyAlgorithm(solvedCube(),invertAlgorithm(primary));const result:string[]=[];
  for(const a of raw) {if(/3/.test(a))continue;const normalized=canonicalOrientation(a);let found:string|undefined;
    outer: for(const y of ['','y','y2',"y'"])for(const u of ['','U','U2',"U'"]) {const candidate=canonicalOrientation([y,u,normalized].filter(Boolean).join(' '));const end=applyAlgorithm(initial,candidate);if(!isF2LSolved(end))continue;
      if(family==='OLL'&&isOLLOriented(end)) {found=candidate;break outer;}
      if(family==='PLL')for(const auf of ['','U','U2',"U'"])if(isSolved(applyAlgorithm(end,auf))){found=[candidate,auf].filter(Boolean).join(' ');break outer;}
    }
    if(found&&found!==primary&&!result.includes(found))result.push(found);
  }return result;
}
const cases: readonly Omit<AlgorithmCase,'aliases'|'nameKind'|'nameSource'>[] = CATALOG_SOURCE.map(raw=>{
  const algorithm=canonicalOrientation(raw.algorithms[0]);const setup=invertAlgorithm(algorithm);
  return {id:raw.family==='OLL'?`OLL-${raw.name.padStart(2,'0')}`:`PLL-${raw.name}`,family:raw.family,name:raw.family==='OLL'?`OLL ${raw.name}`:`PLL ${raw.name}`,group:groups[raw.group]??raw.group,algorithm,alternatives:compatibleAlternatives(raw.algorithms.slice(1),algorithm,raw.family),setup,initialState:applyAlgorithm(solvedCube(),setup),twoLook:raw.family==='OLL'?twoLookOLL.has(raw.name):twoLookPLL.has(raw.name),source:'https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts'};
});

writeFileSync(new URL('../../src/data/catalog-compiled.ts',import.meta.url), '// Generated by tests/domain/compile-catalog.ts from MIT Cube Coach data.\n// See docs/sources-and-licenses.md. Do not edit by hand.\nexport const COMPILED_CASES = '+JSON.stringify(cases.map(({initialState,...c})=>c),null,2)+' as const;\n');
