// Generated by docs/expansion-curation/generate-exercises.mjs.
import type { ExpansionExerciseSource } from '../../domain/types';
export const EXERCISE_SOURCES: readonly ExpansionExerciseSource[] = [
  {
    "id": "cfop/cross/alinhar-uma-aresta",
    "kind": "exercise",
    "family": "CROSS",
    "methodId": "cfop",
    "stageId": "cross",
    "groupId": "cross-practice",
    "group": "Alinhamento",
    "name": "Alinhar a última aresta da cruz",
    "aliases": [
      "alinhar-uma-aresta",
      "cruz branca"
    ],
    "nameKind": "descriptive",
    "nameSource": "Títulos didáticos autorais Nexus Cube; não são nomes universais de casos.",
    "setup": "R U R' F2",
    "solution": "F2",
    "alternatives": [],
    "objective": "Compare a cor verde da aresta branca com o centro F antes de levar branco para D.",
    "preconditions": [
      "U amarelo, D branco, F verde, R vermelho, B azul e L laranja.",
      "Peças já corretas que devem voltar corretas ao final: DR, DB, DL."
    ],
    "preservation": [
      "Ao concluir, preserve DR, DB, DL.",
      "Alguns movimentos podem deslocar temporariamente peças protegidas; confira sua restauração no fim."
    ],
    "milestones": [
      {
        "step": 0,
        "title": "Reconhecer e planejar",
        "explanation": "Compare a cor verde da aresta branca com o centro F antes de levar branco para D. Estado inicial: DF em UF."
      },
      {
        "step": 1,
        "title": "Aresta alinhada",
        "explanation": "Gire a face frontal meia volta. O branco desce junto com sua cor lateral correta. Confira: DF em DF (correto)."
      }
    ],
    "focus": {
      "kind": "pieces",
      "pieces": [
        "DF"
      ],
      "referencePieces": [
        "D",
        "F",
        "R",
        "B",
        "L"
      ]
    },
    "validation": {
      "goal": "cross",
      "preserve": [
        "DR",
        "DB",
        "DL"
      ],
      "referenceFrame": "fixed"
    },
    "provenance": [
      {
        "title": "Corpus didático Nexus Cube",
        "url": "docs/expansion-curation/README.md",
        "author": "Nexus Cube, curadoria Trama",
        "license": "Produção autoral do projeto",
        "notes": "Estados e sequências montados localmente e verificados com KPuzzle e modelo geométrico. Exemplos finitos, não catálogo universal de construções intuitivas."
      },
      {
        "title": "CFOP, sistema da autora",
        "url": "https://ws.binghamton.edu/fridrich/system.html",
        "author": "Jessica Fridrich",
        "license": "Referência factual; sem redistribuição de figuras ou texto"
      }
    ]
  },
  {
    "id": "cfop/cross/arestas-vizinhas",
    "kind": "exercise",
    "family": "CROSS",
    "methodId": "cfop",
    "stageId": "cross",
    "groupId": "cross-practice",
    "group": "Planejamento",
    "name": "Duas arestas vizinhas da cruz",
    "aliases": [
      "arestas-vizinhas",
      "cruz branca"
    ],
    "nameKind": "descriptive",
    "nameSource": "Títulos didáticos autorais Nexus Cube; não são nomes universais de casos.",
    "setup": "R U R' F2 R2",
    "solution": "R2 F2",
    "alternatives": [],
    "objective": "Localize branco/laranja e branco/verde. Resolva uma sem retirar a outra de seu caminho de inserção.",
    "preconditions": [
      "U amarelo, D branco, F verde, R laranja, B azul e L vermelho.",
      "Peças já corretas que devem voltar corretas ao final: DB, DL."
    ],
    "preservation": [
      "Ao concluir, preserve DB, DL.",
      "Alguns movimentos podem deslocar temporariamente peças protegidas; confira sua restauração no fim."
    ],
    "milestones": [
      {
        "step": 0,
        "title": "Reconhecer e planejar",
        "explanation": "Localize branco/laranja e branco/verde. Resolva uma sem retirar a outra de seu caminho de inserção. Estado inicial: DR em UR; DF em UF."
      },
      {
        "step": 1,
        "title": "Primeira inserção",
        "explanation": "Compare DR com os centros D e R. A segunda aresta continua disponível. Confira: DR em DR (correto); DF em UF."
      },
      {
        "step": 2,
        "title": "Cruz alinhada",
        "explanation": "Complete DF e confira também as duas arestas que já estavam corretas. Confira: DR em DR (correto); DF em DF (correto)."
      }
    ],
    "focus": {
      "kind": "pieces",
      "pieces": [
        "DR",
        "DF"
      ],
      "referencePieces": [
        "D",
        "F",
        "R",
        "B",
        "L"
      ]
    },
    "validation": {
      "goal": "cross",
      "preserve": [
        "DB",
        "DL"
      ],
      "referenceFrame": "fixed"
    },
    "provenance": [
      {
        "title": "Corpus didático Nexus Cube",
        "url": "docs/expansion-curation/README.md",
        "author": "Nexus Cube, curadoria Trama",
        "license": "Produção autoral do projeto",
        "notes": "Estados e sequências montados localmente e verificados com KPuzzle e modelo geométrico. Exemplos finitos, não catálogo universal de construções intuitivas."
      },
      {
        "title": "CFOP, sistema da autora",
        "url": "https://ws.binghamton.edu/fridrich/system.html",
        "author": "Jessica Fridrich",
        "license": "Referência factual; sem redistribuição de figuras ou texto"
      }
    ]
  },
  {
    "id": "cfop/cross/arestas-opostas",
    "kind": "exercise",
    "family": "CROSS",
    "methodId": "cfop",
    "stageId": "cross",
    "groupId": "cross-practice",
    "group": "Planejamento",
    "name": "Duas arestas opostas da cruz",
    "aliases": [
      "arestas-opostas",
      "cruz branca"
    ],
    "nameKind": "descriptive",
    "nameSource": "Títulos didáticos autorais Nexus Cube; não são nomes universais de casos.",
    "setup": "R U R' F2 B2",
    "solution": "B2 F2",
    "alternatives": [],
    "objective": "Planeje as arestas opostas branca/azul e branca/verde com D embaixo, sem trocar sua referência de frente.",
    "preconditions": [
      "U amarelo, D branco, F verde, R vermelho, B azul e L laranja.",
      "Peças já corretas que devem voltar corretas ao final: DR, DL."
    ],
    "preservation": [
      "Ao concluir, preserve DR, DL.",
      "Alguns movimentos podem deslocar temporariamente peças protegidas; confira sua restauração no fim."
    ],
    "milestones": [
      {
        "step": 0,
        "title": "Reconhecer e planejar",
        "explanation": "Planeje as arestas opostas branca/azul e branca/verde com D embaixo, sem trocar sua referência de frente. Estado inicial: DB em UB; DF em UF."
      },
      {
        "step": 1,
        "title": "Fundo alinhado",
        "explanation": "A face B leva a aresta ao centro azul; a frente continua livre. Confira: DB em DB (correto); DF em UF."
      },
      {
        "step": 2,
        "title": "Frente alinhada",
        "explanation": "Feche a cruz verificando as quatro cores laterais, não apenas o branco. Confira: DB em DB (correto); DF em DF (correto)."
      }
    ],
    "focus": {
      "kind": "pieces",
      "pieces": [
        "DB",
        "DF"
      ],
      "referencePieces": [
        "D",
        "F",
        "R",
        "B",
        "L"
      ]
    },
    "validation": {
      "goal": "cross",
      "preserve": [
        "DR",
        "DL"
      ],
      "referenceFrame": "fixed"
    },
    "provenance": [
      {
        "title": "Corpus didático Nexus Cube",
        "url": "docs/expansion-curation/README.md",
        "author": "Nexus Cube, curadoria Trama",
        "license": "Produção autoral do projeto",
        "notes": "Estados e sequências montados localmente e verificados com KPuzzle e modelo geométrico. Exemplos finitos, não catálogo universal de construções intuitivas."
      },
      {
        "title": "CFOP, sistema da autora",
        "url": "https://ws.binghamton.edu/fridrich/system.html",
        "author": "Jessica Fridrich",
        "license": "Referência factual; sem redistribuição de figuras ou texto"
      }
    ]
  },
  {
    "id": "cfop/cross/planejar-quatro",
    "kind": "exercise",
    "family": "CROSS",
    "methodId": "cfop",
    "stageId": "cross",
    "groupId": "cross-practice",
    "group": "Cruz completa",
    "name": "Planejar as quatro arestas da cruz",
    "aliases": [
      "planejar-quatro",
      "cruz branca"
    ],
    "nameKind": "descriptive",
    "nameSource": "Títulos didáticos autorais Nexus Cube; não são nomes universais de casos.",
    "setup": "R U R' F2 R2 B2 L2",
    "solution": "L2 B2 R2 F2",
    "alternatives": [],
    "objective": "Rastreie as quatro arestas brancas antes de executar. Este exemplo usa quatro inserções independentes, não representa todos os embaralhamentos.",
    "preconditions": [
      "U amarelo, D branco, F verde, R vermelho, B azul e L laranja.",
      "Peças já corretas que devem voltar corretas ao final: nenhuma exigida neste exemplo."
    ],
    "preservation": [
      "Ao concluir, preserve a referência dos centros.",
      "Alguns movimentos podem deslocar temporariamente peças protegidas; confira sua restauração no fim."
    ],
    "milestones": [
      {
        "step": 0,
        "title": "Reconhecer e planejar",
        "explanation": "Rastreie as quatro arestas brancas antes de executar. Este exemplo usa quatro inserções independentes, não representa todos os embaralhamentos. Estado inicial: DF em UF; DR em UR; DB em UB; DL em UL."
      },
      {
        "step": 1,
        "title": "Esquerda pronta",
        "explanation": "Confira a aresta branca/laranja ao lado do centro L. Confira: DF em UF; DR em UR; DB em UB; DL em DL (correto)."
      },
      {
        "step": 2,
        "title": "Fundo pronto",
        "explanation": "Mantenha a orientação do cubo enquanto identifica a aresta de trás. Confira: DF em UF; DR em UR; DB em DB (correto); DL em DL (correto)."
      },
      {
        "step": 3,
        "title": "Direita pronta",
        "explanation": "Acompanhe a branca/vermelha até DR. Confira: DF em UF; DR em DR (correto); DB em DB (correto); DL em DL (correto)."
      },
      {
        "step": 4,
        "title": "Cruz completa",
        "explanation": "Confira os quatro centros laterais. Os pares F2L continuam sendo a próxima tarefa. Confira: DF em DF (correto); DR em DR (correto); DB em DB (correto); DL em DL (correto)."
      }
    ],
    "focus": {
      "kind": "pieces",
      "pieces": [
        "DF",
        "DR",
        "DB",
        "DL"
      ],
      "referencePieces": [
        "D",
        "F",
        "R",
        "B",
        "L"
      ]
    },
    "validation": {
      "goal": "cross",
      "preserve": [],
      "referenceFrame": "fixed"
    },
    "provenance": [
      {
        "title": "Corpus didático Nexus Cube",
        "url": "docs/expansion-curation/README.md",
        "author": "Nexus Cube, curadoria Trama",
        "license": "Produção autoral do projeto",
        "notes": "Estados e sequências montados localmente e verificados com KPuzzle e modelo geométrico. Exemplos finitos, não catálogo universal de construções intuitivas."
      },
      {
        "title": "CFOP, sistema da autora",
        "url": "https://ws.binghamton.edu/fridrich/system.html",
        "author": "Jessica Fridrich",
        "license": "Referência factual; sem redistribuição de figuras ou texto"
      }
    ]
  },
  {
    "id": "cfop/f2l/par-pronto",
    "kind": "exercise",
    "family": "F2L",
    "methodId": "cfop",
    "stageId": "f2l",
    "groupId": "fundamentals",
    "group": "Fundamentos",
    "name": "Reconhecer e inserir um par pronto",
    "aliases": [
      "par-pronto",
      "fundamentos F2L"
    ],
    "nameKind": "descriptive",
    "nameSource": "Títulos didáticos autorais Nexus Cube; não são nomes universais de casos.",
    "setup": "R U R' U R U2 R' R U R'",
    "solution": "R U' R'",
    "alternatives": [],
    "objective": "O canto branco/vermelho/verde e a aresta vermelho/verde estão unidos: suas cores comuns apontam para as mesmas faces. Insira o conjunto no slot FR.",
    "preconditions": [
      "Cruz branca e os outros três pares resolvidos.",
      "Peças já corretas que devem voltar corretas ao final: DF, DR, DB, DL, FL, BL, DFL, DBL, BR, DBR."
    ],
    "preservation": [
      "Ao concluir, preserve DF, DR, DB, DL, FL, BL, DFL, DBL, BR, DBR.",
      "Alguns movimentos podem deslocar temporariamente peças protegidas; confira sua restauração no fim."
    ],
    "milestones": [
      {
        "step": 0,
        "title": "Reconhecer e planejar",
        "explanation": "O canto branco/vermelho/verde e a aresta vermelho/verde estão unidos: suas cores comuns apontam para as mesmas faces. Insira o conjunto no slot FR. Estado inicial: DFR em ULF (girado); FR em UF."
      },
      {
        "step": 3,
        "title": "Par inserido",
        "explanation": "Confira canto e aresta juntos no slot FR. A cruz e os outros três pares estão preservados. Confira: DFR em DRF (correto); FR em FR (correto)."
      }
    ],
    "focus": {
      "kind": "pieces",
      "pieces": [
        "DFR",
        "FR"
      ],
      "referencePieces": [
        "DF",
        "DR",
        "DB",
        "DL",
        "D",
        "F",
        "R"
      ]
    },
    "validation": {
      "goal": "f2l-pair",
      "targetSlot": "FR",
      "preserve": [
        "DF",
        "DR",
        "DB",
        "DL",
        "FL",
        "BL",
        "DFL",
        "DBL",
        "BR",
        "DBR"
      ],
      "referenceFrame": "fixed"
    },
    "provenance": [
      {
        "title": "Corpus didático Nexus Cube",
        "url": "docs/expansion-curation/README.md",
        "author": "Nexus Cube, curadoria Trama",
        "license": "Produção autoral do projeto",
        "notes": "Estados e sequências montados localmente e verificados com KPuzzle e modelo geométrico. Exemplos finitos, não catálogo universal de construções intuitivas."
      },
      {
        "title": "Semente Sune para o estado residual",
        "url": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts",
        "author": "Luke Jackson, Cube Coach",
        "license": "MIT",
        "notes": "OLL-27 já presente no catálogo licenciado. Usado somente para deixar os cantos superiores pendentes após concluir a tarefa."
      },
      {
        "title": "F2L, exemplos comentados da autora",
        "url": "https://ws.binghamton.edu/fridrich/examples.html",
        "author": "Jessica Fridrich",
        "license": "Referência pedagógica; sem cópia dos exemplos"
      }
    ]
  },
  {
    "id": "cfop/f2l/formar-par",
    "kind": "exercise",
    "family": "F2L",
    "methodId": "cfop",
    "stageId": "f2l",
    "groupId": "fundamentals",
    "group": "Fundamentos",
    "name": "Formar um par com peças separadas",
    "aliases": [
      "formar-par",
      "fundamentos F2L"
    ],
    "nameKind": "descriptive",
    "nameSource": "Títulos didáticos autorais Nexus Cube; não são nomes universais de casos.",
    "setup": "R U R' U R U2 R' R U' R'",
    "solution": "R U R'",
    "alternatives": [],
    "objective": "Encontre primeiro as duas peças pelo conjunto de cores, mesmo separadas na camada superior. Abra o slot para conectá-las antes de fechá-lo.",
    "preconditions": [
      "Cruz branca e os outros três pares resolvidos.",
      "Peças já corretas que devem voltar corretas ao final: DF, DR, DB, DL, FL, BL, DFL, DBL, BR, DBR."
    ],
    "preservation": [
      "Ao concluir, preserve DF, DR, DB, DL, FL, BL, DFL, DBL, BR, DBR.",
      "Alguns movimentos podem deslocar temporariamente peças protegidas; confira sua restauração no fim."
    ],
    "milestones": [
      {
        "step": 0,
        "title": "Reconhecer e planejar",
        "explanation": "Encontre primeiro as duas peças pelo conjunto de cores, mesmo separadas na camada superior. Abra o slot para conectá-las antes de fechá-lo. Estado inicial: DFR em UFR (girado); FR em UB."
      },
      {
        "step": 1,
        "title": "Abrir o slot",
        "explanation": "R coloca o canto na camada de trabalho. Observe onde ficou a aresta correspondente. Confira: DFR em URB (girado); FR em UB."
      },
      {
        "step": 2,
        "title": "Conectar",
        "explanation": "U aproxima a aresta do canto com as duas cores laterais concordando. Confira: DFR em UFR (girado); FR em UR."
      },
      {
        "step": 3,
        "title": "Inserir",
        "explanation": "Feche R e confira o par FR e a cruz. Confira: DFR em DRF (correto); FR em FR (correto)."
      }
    ],
    "focus": {
      "kind": "pieces",
      "pieces": [
        "DFR",
        "FR"
      ],
      "referencePieces": [
        "DF",
        "DR",
        "DB",
        "DL",
        "D",
        "F",
        "R"
      ]
    },
    "validation": {
      "goal": "f2l-pair",
      "targetSlot": "FR",
      "preserve": [
        "DF",
        "DR",
        "DB",
        "DL",
        "FL",
        "BL",
        "DFL",
        "DBL",
        "BR",
        "DBR"
      ],
      "referenceFrame": "fixed"
    },
    "provenance": [
      {
        "title": "Corpus didático Nexus Cube",
        "url": "docs/expansion-curation/README.md",
        "author": "Nexus Cube, curadoria Trama",
        "license": "Produção autoral do projeto",
        "notes": "Estados e sequências montados localmente e verificados com KPuzzle e modelo geométrico. Exemplos finitos, não catálogo universal de construções intuitivas."
      },
      {
        "title": "Semente Sune para o estado residual",
        "url": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts",
        "author": "Luke Jackson, Cube Coach",
        "license": "MIT",
        "notes": "OLL-27 já presente no catálogo licenciado. Usado somente para deixar os cantos superiores pendentes após concluir a tarefa."
      },
      {
        "title": "F2L, exemplos comentados da autora",
        "url": "https://ws.binghamton.edu/fridrich/examples.html",
        "author": "Jessica Fridrich",
        "license": "Referência pedagógica; sem cópia dos exemplos"
      }
    ]
  },
  {
    "id": "cfop/f2l/conexao-incorreta",
    "kind": "exercise",
    "family": "F2L",
    "methodId": "cfop",
    "stageId": "f2l",
    "groupId": "fundamentals",
    "group": "Fundamentos",
    "name": "Desfazer uma conexão incorreta",
    "aliases": [
      "conexao-incorreta",
      "fundamentos F2L"
    ],
    "nameKind": "descriptive",
    "nameSource": "Títulos didáticos autorais Nexus Cube; não são nomes universais de casos.",
    "setup": "R U R' U R U2 R' R U' R' U' R U R'",
    "solution": "R U' R' U R U R'",
    "alternatives": [],
    "objective": "As peças estão vizinhas, mas suas cores comuns não concordam. Separe a conexão, ajuste a camada superior e forme o par correto.",
    "preconditions": [
      "Cruz branca e os outros três pares resolvidos.",
      "Peças já corretas que devem voltar corretas ao final: DF, DR, DB, DL, FL, BL, DFL, DBL, BR, DBR."
    ],
    "preservation": [
      "Ao concluir, preserve DF, DR, DB, DL, FL, BL, DFL, DBL, BR, DBR.",
      "Alguns movimentos podem deslocar temporariamente peças protegidas; confira sua restauração no fim."
    ],
    "milestones": [
      {
        "step": 0,
        "title": "Reconhecer e planejar",
        "explanation": "As peças estão vizinhas, mas suas cores comuns não concordam. Separe a conexão, ajuste a camada superior e forme o par correto. Estado inicial: DFR em URB (girado); FR em UB."
      },
      {
        "step": 3,
        "title": "Separar",
        "explanation": "Compare novamente as cores comuns das duas peças; proximidade sozinha não significa par pronto. Confira: DFR em URB (girado); FR em UL."
      },
      {
        "step": 4,
        "title": "Reposicionar",
        "explanation": "O ajuste U muda a relação entre canto e aresta antes da inserção. Confira: DFR em UFR (girado); FR em UB."
      },
      {
        "step": 7,
        "title": "Conexão correta",
        "explanation": "As duas peças terminam com as cores alinhadas aos centros F e R. Confira: DFR em DRF (correto); FR em FR (correto)."
      }
    ],
    "focus": {
      "kind": "pieces",
      "pieces": [
        "DFR",
        "FR"
      ],
      "referencePieces": [
        "DF",
        "DR",
        "DB",
        "DL",
        "D",
        "F",
        "R"
      ]
    },
    "validation": {
      "goal": "f2l-pair",
      "targetSlot": "FR",
      "preserve": [
        "DF",
        "DR",
        "DB",
        "DL",
        "FL",
        "BL",
        "DFL",
        "DBL",
        "BR",
        "DBR"
      ],
      "referenceFrame": "fixed"
    },
    "provenance": [
      {
        "title": "Corpus didático Nexus Cube",
        "url": "docs/expansion-curation/README.md",
        "author": "Nexus Cube, curadoria Trama",
        "license": "Produção autoral do projeto",
        "notes": "Estados e sequências montados localmente e verificados com KPuzzle e modelo geométrico. Exemplos finitos, não catálogo universal de construções intuitivas."
      },
      {
        "title": "Semente Sune para o estado residual",
        "url": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts",
        "author": "Luke Jackson, Cube Coach",
        "license": "MIT",
        "notes": "OLL-27 já presente no catálogo licenciado. Usado somente para deixar os cantos superiores pendentes após concluir a tarefa."
      },
      {
        "title": "F2L, exemplos comentados da autora",
        "url": "https://ws.binghamton.edu/fridrich/examples.html",
        "author": "Jessica Fridrich",
        "license": "Referência pedagógica; sem cópia dos exemplos"
      }
    ]
  },
  {
    "id": "cfop/f2l/extrair-canto",
    "kind": "exercise",
    "family": "F2L",
    "methodId": "cfop",
    "stageId": "f2l",
    "groupId": "fundamentals",
    "group": "Fundamentos",
    "name": "Extrair um canto preso no slot",
    "aliases": [
      "extrair-canto",
      "fundamentos F2L"
    ],
    "nameKind": "descriptive",
    "nameSource": "Títulos didáticos autorais Nexus Cube; não são nomes universais de casos.",
    "setup": "R U R' U R U2 R' R U' R' U R U' R'",
    "solution": "R U R' U' R U R'",
    "alternatives": [],
    "objective": "O canto correto está em DFR, mas girado; a aresta correspondente está em U. Retire o canto para trabalhar o par fora do slot.",
    "preconditions": [
      "Cruz branca e os outros três pares resolvidos.",
      "Peças já corretas que devem voltar corretas ao final: DF, DR, DB, DL, FL, BL, DFL, DBL, BR, DBR."
    ],
    "preservation": [
      "Ao concluir, preserve DF, DR, DB, DL, FL, BL, DFL, DBL, BR, DBR.",
      "Alguns movimentos podem deslocar temporariamente peças protegidas; confira sua restauração no fim."
    ],
    "milestones": [
      {
        "step": 0,
        "title": "Reconhecer e planejar",
        "explanation": "O canto correto está em DFR, mas girado; a aresta correspondente está em U. Retire o canto para trabalhar o par fora do slot. Estado inicial: DFR em DRF (girado); FR em UR."
      },
      {
        "step": 3,
        "title": "Canto acessível",
        "explanation": "O canto sai do slot para a camada superior. Continue acompanhando sua identidade. Confira: DFR em ULF (girado); FR em UR."
      },
      {
        "step": 4,
        "title": "Ajustar o par",
        "explanation": "Use U para preparar a relação de cores exigida pela inserção. Confira: DFR em UFR (girado); FR em UB."
      },
      {
        "step": 7,
        "title": "Slot concluído",
        "explanation": "Canto e aresta agora têm posição e orientação corretas. Confira: DFR em DRF (correto); FR em FR (correto)."
      }
    ],
    "focus": {
      "kind": "pieces",
      "pieces": [
        "DFR",
        "FR"
      ],
      "referencePieces": [
        "DF",
        "DR",
        "DB",
        "DL",
        "D",
        "F",
        "R"
      ]
    },
    "validation": {
      "goal": "f2l-pair",
      "targetSlot": "FR",
      "preserve": [
        "DF",
        "DR",
        "DB",
        "DL",
        "FL",
        "BL",
        "DFL",
        "DBL",
        "BR",
        "DBR"
      ],
      "referenceFrame": "fixed"
    },
    "provenance": [
      {
        "title": "Corpus didático Nexus Cube",
        "url": "docs/expansion-curation/README.md",
        "author": "Nexus Cube, curadoria Trama",
        "license": "Produção autoral do projeto",
        "notes": "Estados e sequências montados localmente e verificados com KPuzzle e modelo geométrico. Exemplos finitos, não catálogo universal de construções intuitivas."
      },
      {
        "title": "Semente Sune para o estado residual",
        "url": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts",
        "author": "Luke Jackson, Cube Coach",
        "license": "MIT",
        "notes": "OLL-27 já presente no catálogo licenciado. Usado somente para deixar os cantos superiores pendentes após concluir a tarefa."
      },
      {
        "title": "F2L, exemplos comentados da autora",
        "url": "https://ws.binghamton.edu/fridrich/examples.html",
        "author": "Jessica Fridrich",
        "license": "Referência pedagógica; sem cópia dos exemplos"
      }
    ]
  },
  {
    "id": "roux/fb/aresta-base",
    "kind": "exercise",
    "family": "FB",
    "methodId": "roux",
    "stageId": "fb",
    "groupId": "first-block-practice",
    "group": "Base do primeiro bloco",
    "name": "Localizar a aresta base DL",
    "aliases": [
      "aresta-base",
      "primeiro bloco"
    ],
    "nameKind": "descriptive",
    "nameSource": "Títulos didáticos autorais Nexus Cube; não são nomes universais de casos.",
    "setup": "R U R' L2",
    "solution": "L2",
    "alternatives": [],
    "objective": "Encontre a aresta branca/laranja e os centros D e L. Neste exemplo as outras peças já estão agrupadas na face L; uma meia volta coloca o bloco inteiro.",
    "preconditions": [
      "U amarelo, D branco, F verde, R vermelho, B azul e L laranja.",
      "Peças já corretas que devem voltar corretas ao final: nenhuma exigida neste exemplo."
    ],
    "preservation": [
      "Ao concluir, preserve a referência dos centros.",
      "Alguns movimentos podem deslocar temporariamente peças protegidas; confira sua restauração no fim."
    ],
    "milestones": [
      {
        "step": 0,
        "title": "Reconhecer e planejar",
        "explanation": "Encontre a aresta branca/laranja e os centros D e L. Neste exemplo as outras peças já estão agrupadas na face L; uma meia volta coloca o bloco inteiro. Estado inicial: DL em UL; DFL em UBL; DBL em ULF; FL em BL; BL em FL."
      },
      {
        "step": 1,
        "title": "Base e bloco alinhados",
        "explanation": "Confira DL entre os centros branco e laranja e reconheça os dois pares que vieram junto. Confira: DL em DL (correto); DFL em DFL (correto); DBL em DLB (correto); FL em FL (correto); BL em BL (correto)."
      }
    ],
    "focus": {
      "kind": "pieces",
      "pieces": [
        "DL",
        "DFL",
        "DBL",
        "FL",
        "BL"
      ],
      "referencePieces": [
        "D",
        "L"
      ]
    },
    "validation": {
      "goal": "first-block",
      "preserve": [],
      "referenceFrame": "fixed"
    },
    "provenance": [
      {
        "title": "Corpus didático Nexus Cube",
        "url": "docs/expansion-curation/README.md",
        "author": "Nexus Cube, curadoria Trama",
        "license": "Produção autoral do projeto",
        "notes": "Estados e sequências montados localmente e verificados com KPuzzle e modelo geométrico. Exemplos finitos, não catálogo universal de construções intuitivas."
      },
      {
        "title": "Primeiro bloco, método original",
        "url": "http://grrroux.free.fr/method/Step_1.html",
        "author": "Gilles Roux",
        "license": "Referência factual; sem cópia de exemplos ou assets"
      }
    ]
  },
  {
    "id": "roux/fb/quadrado-frontal",
    "kind": "exercise",
    "family": "FB",
    "methodId": "roux",
    "stageId": "fb",
    "groupId": "first-block-practice",
    "group": "Quadrados e pares",
    "name": "Completar o quadrado frontal esquerdo",
    "aliases": [
      "quadrado-frontal",
      "primeiro bloco"
    ],
    "nameKind": "descriptive",
    "nameSource": "Títulos didáticos autorais Nexus Cube; não são nomes universais de casos.",
    "setup": "R U R' L' U L",
    "solution": "L' U' L",
    "alternatives": [],
    "objective": "A aresta DL serve de apoio. Relacione o canto branco/laranja/verde à aresta laranja/verde e insira o par junto da base.",
    "preconditions": [
      "U amarelo, D branco, F verde, R vermelho, B azul e L laranja.",
      "Peças já corretas que devem voltar corretas ao final: DL, BL, DBL."
    ],
    "preservation": [
      "Ao concluir, preserve DL, BL, DBL.",
      "Alguns movimentos podem deslocar temporariamente peças protegidas; confira sua restauração no fim."
    ],
    "milestones": [
      {
        "step": 0,
        "title": "Reconhecer e planejar",
        "explanation": "A aresta DL serve de apoio. Relacione o canto branco/laranja/verde à aresta laranja/verde e insira o par junto da base. Estado inicial: DL em DL (correto); DFL em ULF (girado); FL em UB."
      },
      {
        "step": 3,
        "title": "Quadrado 1×2×2",
        "explanation": "DL, DFL e FL formam o quadrado frontal. O par traseiro que já estava pronto completa o bloco deste exemplo. Confira: DL em DL (correto); DFL em DFL (correto); FL em FL (correto)."
      }
    ],
    "focus": {
      "kind": "pieces",
      "pieces": [
        "DL",
        "DFL",
        "FL"
      ],
      "referencePieces": [
        "D",
        "L"
      ]
    },
    "validation": {
      "goal": "first-block",
      "preserve": [
        "DL",
        "BL",
        "DBL"
      ],
      "referenceFrame": "fixed"
    },
    "provenance": [
      {
        "title": "Corpus didático Nexus Cube",
        "url": "docs/expansion-curation/README.md",
        "author": "Nexus Cube, curadoria Trama",
        "license": "Produção autoral do projeto",
        "notes": "Estados e sequências montados localmente e verificados com KPuzzle e modelo geométrico. Exemplos finitos, não catálogo universal de construções intuitivas."
      },
      {
        "title": "Primeiro bloco, método original",
        "url": "http://grrroux.free.fr/method/Step_1.html",
        "author": "Gilles Roux",
        "license": "Referência factual; sem cópia de exemplos ou assets"
      }
    ]
  },
  {
    "id": "roux/fb/par-traseiro",
    "kind": "exercise",
    "family": "FB",
    "methodId": "roux",
    "stageId": "fb",
    "groupId": "first-block-practice",
    "group": "Quadrados e pares",
    "name": "Adicionar o par traseiro esquerdo",
    "aliases": [
      "par-traseiro",
      "primeiro bloco"
    ],
    "nameKind": "descriptive",
    "nameSource": "Títulos didáticos autorais Nexus Cube; não são nomes universais de casos.",
    "setup": "R U R' L U' L'",
    "solution": "L U L'",
    "alternatives": [],
    "objective": "Preserve o quadrado frontal e procure o canto branco/laranja/azul e a aresta laranja/azul. A referência B é azul.",
    "preconditions": [
      "U amarelo, D branco, F verde, R vermelho, B azul e L laranja.",
      "Peças já corretas que devem voltar corretas ao final: DL, FL, DFL."
    ],
    "preservation": [
      "Ao concluir, preserve DL, FL, DFL.",
      "Alguns movimentos podem deslocar temporariamente peças protegidas; confira sua restauração no fim."
    ],
    "milestones": [
      {
        "step": 0,
        "title": "Reconhecer e planejar",
        "explanation": "Preserve o quadrado frontal e procure o canto branco/laranja/azul e a aresta laranja/azul. A referência B é azul. Estado inicial: DL em DL (correto); DBL em UBL (girado); BL em UF."
      },
      {
        "step": 3,
        "title": "Primeiro bloco 1×2×3",
        "explanation": "Confira os dois cantos e as três arestas do bloco esquerdo. A região direita permanece livre para SB. Confira: DL em DL (correto); DBL em DLB (correto); BL em BL (correto)."
      }
    ],
    "focus": {
      "kind": "pieces",
      "pieces": [
        "DL",
        "DBL",
        "BL"
      ],
      "referencePieces": [
        "D",
        "L"
      ]
    },
    "validation": {
      "goal": "first-block",
      "preserve": [
        "DL",
        "FL",
        "DFL"
      ],
      "referenceFrame": "fixed"
    },
    "provenance": [
      {
        "title": "Corpus didático Nexus Cube",
        "url": "docs/expansion-curation/README.md",
        "author": "Nexus Cube, curadoria Trama",
        "license": "Produção autoral do projeto",
        "notes": "Estados e sequências montados localmente e verificados com KPuzzle e modelo geométrico. Exemplos finitos, não catálogo universal de construções intuitivas."
      },
      {
        "title": "Primeiro bloco, método original",
        "url": "http://grrroux.free.fr/method/Step_1.html",
        "author": "Gilles Roux",
        "license": "Referência factual; sem cópia de exemplos ou assets"
      }
    ]
  },
  {
    "id": "roux/fb/construir-bloco",
    "kind": "exercise",
    "family": "FB",
    "methodId": "roux",
    "stageId": "fb",
    "groupId": "first-block-practice",
    "group": "Bloco completo",
    "name": "Construir o primeiro bloco por etapas",
    "aliases": [
      "construir-bloco",
      "primeiro bloco"
    ],
    "nameKind": "descriptive",
    "nameSource": "Títulos didáticos autorais Nexus Cube; não são nomes universais de casos.",
    "setup": "R U R' L U' L' L' U L L2",
    "solution": "L2 L' U' L L U L'",
    "alternatives": [],
    "objective": "Planeje base DL, par frontal e par traseiro. Esta construção guiada mostra o percurso inteiro; outras posições exigem escolhas intuitivas diferentes.",
    "preconditions": [
      "U amarelo, D branco, F verde, R vermelho, B azul e L laranja.",
      "Peças já corretas que devem voltar corretas ao final: BL."
    ],
    "preservation": [
      "Ao concluir, preserve BL.",
      "Alguns movimentos podem deslocar temporariamente peças protegidas; confira sua restauração no fim."
    ],
    "milestones": [
      {
        "step": 0,
        "title": "Reconhecer e planejar",
        "explanation": "Planeje base DL, par frontal e par traseiro. Esta construção guiada mostra o percurso inteiro; outras posições exigem escolhas intuitivas diferentes. Estado inicial: DL em UL; FL em UB; BL em BL (correto); DFL em DLB (girado); DBL em DFL (girado)."
      },
      {
        "step": 1,
        "title": "Fixar a base",
        "explanation": "DL chega ao lugar correto. Procure o par frontal sem mudar os centros de referência. Confira: DL em DL (correto); FL em UB; BL em FL; DFL em ULF (girado); DBL em UBL (girado)."
      },
      {
        "step": 4,
        "title": "Completar a frente",
        "explanation": "O quadrado frontal fica pronto; a próxima busca é pelo par de trás. Confira: DL em DL (correto); FL em FL (correto); BL em UF; DFL em DFL (correto); DBL em UBL (girado)."
      },
      {
        "step": 7,
        "title": "Fechar o bloco",
        "explanation": "Verifique as cinco peças do bloco esquerdo. Use o espaço livre à direita para construir SB. Confira: DL em DL (correto); FL em FL (correto); BL em BL (correto); DFL em DFL (correto); DBL em DLB (correto)."
      }
    ],
    "focus": {
      "kind": "pieces",
      "pieces": [
        "DL",
        "FL",
        "BL",
        "DFL",
        "DBL"
      ],
      "referencePieces": [
        "D",
        "L"
      ]
    },
    "validation": {
      "goal": "first-block",
      "preserve": [
        "BL"
      ],
      "referenceFrame": "fixed"
    },
    "provenance": [
      {
        "title": "Corpus didático Nexus Cube",
        "url": "docs/expansion-curation/README.md",
        "author": "Nexus Cube, curadoria Trama",
        "license": "Produção autoral do projeto",
        "notes": "Estados e sequências montados localmente e verificados com KPuzzle e modelo geométrico. Exemplos finitos, não catálogo universal de construções intuitivas."
      },
      {
        "title": "Primeiro bloco, método original",
        "url": "http://grrroux.free.fr/method/Step_1.html",
        "author": "Gilles Roux",
        "license": "Referência factual; sem cópia de exemplos ou assets"
      }
    ]
  },
  {
    "id": "roux/sb/aresta-base",
    "kind": "exercise",
    "family": "SB",
    "methodId": "roux",
    "stageId": "sb",
    "groupId": "second-block-practice",
    "group": "Base do segundo bloco",
    "name": "Assentar a base DR preservando FB",
    "aliases": [
      "aresta-base",
      "segundo bloco"
    ],
    "nameKind": "descriptive",
    "nameSource": "Títulos didáticos autorais Nexus Cube; não são nomes universais de casos.",
    "setup": "R U R' U R U2 R' R2",
    "solution": "R2",
    "alternatives": [],
    "objective": "Use o bloco esquerdo como referência fixa. As peças direitas estão agrupadas neste exemplo; R2 assenta DR e os dois pares.",
    "preconditions": [
      "Primeiro bloco esquerdo resolvido.",
      "Peças já corretas que devem voltar corretas ao final: DL, FL, BL, DFL, DBL."
    ],
    "preservation": [
      "Ao concluir, preserve DL, FL, BL, DFL, DBL.",
      "Alguns movimentos podem deslocar temporariamente peças protegidas; confira sua restauração no fim."
    ],
    "milestones": [
      {
        "step": 0,
        "title": "Reconhecer e planejar",
        "explanation": "Use o bloco esquerdo como referência fixa. As peças direitas estão agrupadas neste exemplo; R2 assenta DR e os dois pares. Estado inicial: DR em UR; FR em BR; BR em FR; DFR em URB; DBR em UFR."
      },
      {
        "step": 1,
        "title": "Base direita assentada",
        "explanation": "Confira DR e os centros D/R. O bloco esquerdo retorna intacto e os cantos superiores ficam para CMLL. Confira: DR em DR (correto); FR em FR (correto); BR em BR (correto); DFR em DRF (correto); DBR em DBR (correto)."
      }
    ],
    "focus": {
      "kind": "pieces",
      "pieces": [
        "DR",
        "FR",
        "BR",
        "DFR",
        "DBR"
      ],
      "referencePieces": [
        "DL",
        "FL",
        "BL",
        "DFL",
        "DBL",
        "D",
        "R"
      ]
    },
    "validation": {
      "goal": "second-block",
      "preserve": [
        "DL",
        "FL",
        "BL",
        "DFL",
        "DBL"
      ],
      "referenceFrame": "fixed"
    },
    "provenance": [
      {
        "title": "Corpus didático Nexus Cube",
        "url": "docs/expansion-curation/README.md",
        "author": "Nexus Cube, curadoria Trama",
        "license": "Produção autoral do projeto",
        "notes": "Estados e sequências montados localmente e verificados com KPuzzle e modelo geométrico. Exemplos finitos, não catálogo universal de construções intuitivas."
      },
      {
        "title": "Semente Sune para o estado residual",
        "url": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts",
        "author": "Luke Jackson, Cube Coach",
        "license": "MIT",
        "notes": "OLL-27 já presente no catálogo licenciado. Usado somente para deixar os cantos superiores pendentes após concluir a tarefa."
      },
      {
        "title": "Segundo bloco, método original",
        "url": "http://grrroux.free.fr/method/Step_2.html",
        "author": "Gilles Roux",
        "license": "Referência factual; sem cópia de exemplos ou assets"
      }
    ]
  },
  {
    "id": "roux/sb/quadrado-frontal",
    "kind": "exercise",
    "family": "SB",
    "methodId": "roux",
    "stageId": "sb",
    "groupId": "second-block-practice",
    "group": "Quadrados e pares",
    "name": "Montar o quadrado frontal direito",
    "aliases": [
      "quadrado-frontal",
      "segundo bloco"
    ],
    "nameKind": "descriptive",
    "nameSource": "Títulos didáticos autorais Nexus Cube; não são nomes universais de casos.",
    "setup": "R U R' U R U2 R' R U' R'",
    "solution": "R U R'",
    "alternatives": [],
    "objective": "Com FB pronto, encontre canto branco/vermelho/verde e aresta vermelho/verde. Use DR como apoio para o quadrado direito.",
    "preconditions": [
      "Primeiro bloco esquerdo resolvido.",
      "Peças já corretas que devem voltar corretas ao final: DL, FL, BL, DFL, DBL, DR, BR, DBR."
    ],
    "preservation": [
      "Ao concluir, preserve DL, FL, BL, DFL, DBL, DR, BR, DBR.",
      "Alguns movimentos podem deslocar temporariamente peças protegidas; confira sua restauração no fim."
    ],
    "milestones": [
      {
        "step": 0,
        "title": "Reconhecer e planejar",
        "explanation": "Com FB pronto, encontre canto branco/vermelho/verde e aresta vermelho/verde. Use DR como apoio para o quadrado direito. Estado inicial: DR em DR (correto); DFR em UFR (girado); FR em UB."
      },
      {
        "step": 3,
        "title": "Quadrado direito pronto",
        "explanation": "DR, DFR e FR concordam com os centros. Confira também o bloco esquerdo preservado. Confira: DR em DR (correto); DFR em DRF (correto); FR em FR (correto)."
      }
    ],
    "focus": {
      "kind": "pieces",
      "pieces": [
        "DR",
        "DFR",
        "FR"
      ],
      "referencePieces": [
        "DL",
        "FL",
        "BL",
        "DFL",
        "DBL",
        "D",
        "R"
      ]
    },
    "validation": {
      "goal": "second-block",
      "preserve": [
        "DL",
        "FL",
        "BL",
        "DFL",
        "DBL",
        "DR",
        "BR",
        "DBR"
      ],
      "referenceFrame": "fixed"
    },
    "provenance": [
      {
        "title": "Corpus didático Nexus Cube",
        "url": "docs/expansion-curation/README.md",
        "author": "Nexus Cube, curadoria Trama",
        "license": "Produção autoral do projeto",
        "notes": "Estados e sequências montados localmente e verificados com KPuzzle e modelo geométrico. Exemplos finitos, não catálogo universal de construções intuitivas."
      },
      {
        "title": "Semente Sune para o estado residual",
        "url": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts",
        "author": "Luke Jackson, Cube Coach",
        "license": "MIT",
        "notes": "OLL-27 já presente no catálogo licenciado. Usado somente para deixar os cantos superiores pendentes após concluir a tarefa."
      },
      {
        "title": "Segundo bloco, método original",
        "url": "http://grrroux.free.fr/method/Step_2.html",
        "author": "Gilles Roux",
        "license": "Referência factual; sem cópia de exemplos ou assets"
      }
    ]
  },
  {
    "id": "roux/sb/par-traseiro",
    "kind": "exercise",
    "family": "SB",
    "methodId": "roux",
    "stageId": "sb",
    "groupId": "second-block-practice",
    "group": "Quadrados e pares",
    "name": "Fechar o segundo bloco por trás",
    "aliases": [
      "par-traseiro",
      "segundo bloco"
    ],
    "nameKind": "descriptive",
    "nameSource": "Títulos didáticos autorais Nexus Cube; não são nomes universais de casos.",
    "setup": "R U R' U R U2 R' R' U R",
    "solution": "R' U' R",
    "alternatives": [],
    "objective": "Trabalhe o canto branco/vermelho/azul com a aresta vermelho/azul. A conclusão deve preservar o primeiro bloco e o quadrado frontal direito.",
    "preconditions": [
      "Primeiro bloco esquerdo resolvido.",
      "Peças já corretas que devem voltar corretas ao final: DL, FL, BL, DFL, DBL, DR, FR, DFR."
    ],
    "preservation": [
      "Ao concluir, preserve DL, FL, BL, DFL, DBL, DR, FR, DFR.",
      "Alguns movimentos podem deslocar temporariamente peças protegidas; confira sua restauração no fim."
    ],
    "milestones": [
      {
        "step": 0,
        "title": "Reconhecer e planejar",
        "explanation": "Trabalhe o canto branco/vermelho/azul com a aresta vermelho/azul. A conclusão deve preservar o primeiro bloco e o quadrado frontal direito. Estado inicial: DR em DR (correto); DBR em URB (girado); BR em UF."
      },
      {
        "step": 3,
        "title": "Dois blocos completos",
        "explanation": "Confira os dois blocos 1×2×3. A camada M pode continuar livre; os quatro cantos de U definem CMLL. Confira: DR em DR (correto); DBR em DBR (correto); BR em BR (correto)."
      }
    ],
    "focus": {
      "kind": "pieces",
      "pieces": [
        "DR",
        "DBR",
        "BR"
      ],
      "referencePieces": [
        "DL",
        "FL",
        "BL",
        "DFL",
        "DBL",
        "D",
        "R"
      ]
    },
    "validation": {
      "goal": "second-block",
      "preserve": [
        "DL",
        "FL",
        "BL",
        "DFL",
        "DBL",
        "DR",
        "FR",
        "DFR"
      ],
      "referenceFrame": "fixed"
    },
    "provenance": [
      {
        "title": "Corpus didático Nexus Cube",
        "url": "docs/expansion-curation/README.md",
        "author": "Nexus Cube, curadoria Trama",
        "license": "Produção autoral do projeto",
        "notes": "Estados e sequências montados localmente e verificados com KPuzzle e modelo geométrico. Exemplos finitos, não catálogo universal de construções intuitivas."
      },
      {
        "title": "Semente Sune para o estado residual",
        "url": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts",
        "author": "Luke Jackson, Cube Coach",
        "license": "MIT",
        "notes": "OLL-27 já presente no catálogo licenciado. Usado somente para deixar os cantos superiores pendentes após concluir a tarefa."
      },
      {
        "title": "Segundo bloco, método original",
        "url": "http://grrroux.free.fr/method/Step_2.html",
        "author": "Gilles Roux",
        "license": "Referência factual; sem cópia de exemplos ou assets"
      }
    ]
  },
  {
    "id": "roux/sb/construir-bloco",
    "kind": "exercise",
    "family": "SB",
    "methodId": "roux",
    "stageId": "sb",
    "groupId": "second-block-practice",
    "group": "Bloco completo",
    "name": "Construir SB sem perder FB",
    "aliases": [
      "construir-bloco",
      "segundo bloco"
    ],
    "nameKind": "descriptive",
    "nameSource": "Títulos didáticos autorais Nexus Cube; não são nomes universais de casos.",
    "setup": "R U R' U R U2 R' R' U R R U' R' R2",
    "solution": "R2 R U R' R' U' R",
    "alternatives": [],
    "objective": "Siga DR, par frontal e par traseiro, mantendo o bloco esquerdo como região protegida em cada marco.",
    "preconditions": [
      "Primeiro bloco esquerdo resolvido.",
      "Peças já corretas que devem voltar corretas ao final: DL, FL, BL, DFL, DBL, BR."
    ],
    "preservation": [
      "Ao concluir, preserve DL, FL, BL, DFL, DBL, BR.",
      "Alguns movimentos podem deslocar temporariamente peças protegidas; confira sua restauração no fim."
    ],
    "milestones": [
      {
        "step": 0,
        "title": "Reconhecer e planejar",
        "explanation": "Siga DR, par frontal e par traseiro, mantendo o bloco esquerdo como região protegida em cada marco. Estado inicial: DR em UR; FR em UB; BR em BR (correto); DFR em DBR (girado); DBR em DRF (girado)."
      },
      {
        "step": 1,
        "title": "Base DR",
        "explanation": "A aresta branca/vermelha chega à posição de apoio. Confira: DR em DR (correto); FR em UB; BR em FR; DFR em UFR (girado); DBR em URB (girado)."
      },
      {
        "step": 4,
        "title": "Frente direita",
        "explanation": "O quadrado frontal está pronto; procure a dupla vermelha/azul. Confira: DR em DR (correto); FR em FR (correto); BR em UF; DFR em DRF (correto); DBR em URB (girado)."
      },
      {
        "step": 7,
        "title": "Segundo bloco completo",
        "explanation": "Ambos os blocos estão resolvidos. Reconheça os cantos superiores e siga para CMLL. Confira: DR em DR (correto); FR em FR (correto); BR em BR (correto); DFR em DRF (correto); DBR em DBR (correto)."
      }
    ],
    "focus": {
      "kind": "pieces",
      "pieces": [
        "DR",
        "FR",
        "BR",
        "DFR",
        "DBR"
      ],
      "referencePieces": [
        "DL",
        "FL",
        "BL",
        "DFL",
        "DBL",
        "D",
        "R"
      ]
    },
    "validation": {
      "goal": "second-block",
      "preserve": [
        "DL",
        "FL",
        "BL",
        "DFL",
        "DBL",
        "BR"
      ],
      "referenceFrame": "fixed"
    },
    "provenance": [
      {
        "title": "Corpus didático Nexus Cube",
        "url": "docs/expansion-curation/README.md",
        "author": "Nexus Cube, curadoria Trama",
        "license": "Produção autoral do projeto",
        "notes": "Estados e sequências montados localmente e verificados com KPuzzle e modelo geométrico. Exemplos finitos, não catálogo universal de construções intuitivas."
      },
      {
        "title": "Semente Sune para o estado residual",
        "url": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts",
        "author": "Luke Jackson, Cube Coach",
        "license": "MIT",
        "notes": "OLL-27 já presente no catálogo licenciado. Usado somente para deixar os cantos superiores pendentes após concluir a tarefa."
      },
      {
        "title": "Segundo bloco, método original",
        "url": "http://grrroux.free.fr/method/Step_2.html",
        "author": "Gilles Roux",
        "license": "Referência factual; sem cópia de exemplos ou assets"
      }
    ]
  },
  {
    "id": "roux/lse/referencia-centros",
    "kind": "exercise",
    "family": "LSE",
    "methodId": "roux",
    "stageId": "lse",
    "groupId": "eo",
    "group": "Orientação de arestas",
    "name": "Restaurar a referência dos centros",
    "aliases": [
      "referencia-centros",
      "últimas seis arestas"
    ],
    "nameKind": "descriptive",
    "nameSource": "Títulos didáticos autorais Nexus Cube; não são nomes universais de casos.",
    "setup": "U M U2 M' U' M U2 M' M'",
    "solution": "M",
    "alternatives": [],
    "objective": "Antes de contar arestas ruins, coloque um centro branco ou amarelo no eixo vertical. Aqui um quarto de volta M restaura essa referência e já orienta as seis arestas.",
    "preconditions": [
      "Dois blocos e todos os cantos resolvidos na referência fixa.",
      "Peças já corretas que devem voltar corretas ao final: DL, FL, BL, DFL, DBL, DR, FR, BR, DFR, DBR, UFR, URB, UBL, ULF."
    ],
    "preservation": [
      "Ao concluir, preserve DL, FL, BL, DFL, DBL, DR, FR, BR, DFR, DBR, UFR, URB, UBL, ULF.",
      "Alguns movimentos podem deslocar temporariamente peças protegidas; confira sua restauração no fim."
    ],
    "milestones": [
      {
        "step": 0,
        "title": "Reconhecer e planejar",
        "explanation": "Antes de contar arestas ruins, coloque um centro branco ou amarelo no eixo vertical. Aqui um quarto de volta M restaura essa referência e já orienta as seis arestas. Estado inicial: UF em DF (girado); UR em UL; UB em UB (girado); UL em DB (girado); DF em UF (girado); DB em UR; U em B; D em F; F em U; B em D."
      },
      {
        "step": 1,
        "title": "Referência válida",
        "explanation": "Os centros U/D estão no eixo vertical e todos os adesivos brancos/amarelos das seis arestas apontam para cima ou para baixo. UL/UR ainda são a próxima tarefa. Confira: UF em DB; UR em UL; UB em UF; UL em UB; DF em DF (correto); DB em UR; U em U (correto); D em D (correto); F em F (correto); B em B (correto)."
      }
    ],
    "focus": {
      "kind": "pieces",
      "pieces": [
        "UF",
        "UR",
        "UB",
        "UL",
        "DF",
        "DB",
        "U",
        "D",
        "F",
        "B"
      ],
      "referencePieces": [
        "DL",
        "FL",
        "BL",
        "DFL",
        "DBL",
        "DR",
        "FR",
        "BR",
        "DFR",
        "DBR",
        "UFR",
        "URB",
        "UBL",
        "ULF",
        "U",
        "D"
      ]
    },
    "validation": {
      "goal": "lse-eo",
      "preserve": [
        "DL",
        "FL",
        "BL",
        "DFL",
        "DBL",
        "DR",
        "FR",
        "BR",
        "DFR",
        "DBR",
        "UFR",
        "URB",
        "UBL",
        "ULF"
      ],
      "referenceFrame": "fixed"
    },
    "provenance": [
      {
        "title": "Corpus didático Nexus Cube",
        "url": "docs/expansion-curation/README.md",
        "author": "Nexus Cube, curadoria Trama",
        "license": "Produção autoral do projeto",
        "notes": "Estados e sequências montados localmente e verificados com KPuzzle e modelo geométrico. Exemplos finitos, não catálogo universal de construções intuitivas."
      },
      {
        "title": "Últimas seis arestas, método original",
        "url": "http://grrroux.free.fr/method/Step_4.html",
        "author": "Gilles Roux",
        "license": "Referência factual; sem cópia de exemplos ou assets"
      },
      {
        "title": "LSE, referência vertical e progressão",
        "url": "https://tutorial.rouxers.com/beginners/lse.html",
        "author": "Rouxers",
        "license": "Referência factual; explicação e estados próprios do Nexus Cube"
      }
    ]
  },
  {
    "id": "roux/lse/eo-duas",
    "kind": "exercise",
    "family": "LSE",
    "methodId": "roux",
    "stageId": "lse",
    "groupId": "eo",
    "group": "Orientação de arestas",
    "name": "EO com duas arestas ruins",
    "aliases": [
      "eo-duas",
      "últimas seis arestas"
    ],
    "nameKind": "descriptive",
    "nameSource": "Títulos didáticos autorais Nexus Cube; não são nomes universais de casos.",
    "setup": "U M U2 M' U' M U2 M' U M U' M' U M U' M'",
    "solution": "M U M' U' M U M' U'",
    "alternatives": [],
    "objective": "Com centros U/D no eixo vertical, conte duas arestas cujo adesivo branco/amarelo aponta de lado. Um bloco de movimentos transforma a distribuição; o seguinte conclui EO.",
    "preconditions": [
      "Dois blocos e todos os cantos resolvidos na referência fixa.",
      "Peças já corretas que devem voltar corretas ao final: DL, FL, BL, DFL, DBL, DR, FR, BR, DFR, DBR, UFR, URB, UBL, ULF."
    ],
    "preservation": [
      "Ao concluir, preserve DL, FL, BL, DFL, DBL, DR, FR, BR, DFR, DBR, UFR, URB, UBL, ULF.",
      "Alguns movimentos podem deslocar temporariamente peças protegidas; confira sua restauração no fim."
    ],
    "milestones": [
      {
        "step": 0,
        "title": "Reconhecer e planejar",
        "explanation": "Com centros U/D no eixo vertical, conte duas arestas cujo adesivo branco/amarelo aponta de lado. Um bloco de movimentos transforma a distribuição; o seguinte conclui EO. Estado inicial: UF em UR; UR em UF (girado); UB em DB; UL em UL (correto); DF em DF (correto); DB em UB (girado)."
      },
      {
        "step": 4,
        "title": "Redistribuir a orientação",
        "explanation": "Reconte as arestas ruins ao fim deste bloco e acompanhe as identidades destacadas. Confira: UF em UL (girado); UR em UR (girado); UB em UB (girado); UL em DB (girado); DF em DF (correto); DB em UF."
      },
      {
        "step": 8,
        "title": "EO concluída",
        "explanation": "Todas as seis arestas têm branco/amarelo no eixo vertical. Permutação e UL/UR ainda podem estar erradas. Confira: UF em DB; UR em UL; UB em UF; UL em UB; DF em DF (correto); DB em UR."
      }
    ],
    "focus": {
      "kind": "pieces",
      "pieces": [
        "UF",
        "UR",
        "UB",
        "UL",
        "DF",
        "DB"
      ],
      "referencePieces": [
        "DL",
        "FL",
        "BL",
        "DFL",
        "DBL",
        "DR",
        "FR",
        "BR",
        "DFR",
        "DBR",
        "UFR",
        "URB",
        "UBL",
        "ULF",
        "U",
        "D"
      ]
    },
    "validation": {
      "goal": "lse-eo",
      "preserve": [
        "DL",
        "FL",
        "BL",
        "DFL",
        "DBL",
        "DR",
        "FR",
        "BR",
        "DFR",
        "DBR",
        "UFR",
        "URB",
        "UBL",
        "ULF"
      ],
      "referenceFrame": "fixed"
    },
    "provenance": [
      {
        "title": "Corpus didático Nexus Cube",
        "url": "docs/expansion-curation/README.md",
        "author": "Nexus Cube, curadoria Trama",
        "license": "Produção autoral do projeto",
        "notes": "Estados e sequências montados localmente e verificados com KPuzzle e modelo geométrico. Exemplos finitos, não catálogo universal de construções intuitivas."
      },
      {
        "title": "Últimas seis arestas, método original",
        "url": "http://grrroux.free.fr/method/Step_4.html",
        "author": "Gilles Roux",
        "license": "Referência factual; sem cópia de exemplos ou assets"
      },
      {
        "title": "LSE, referência vertical e progressão",
        "url": "https://tutorial.rouxers.com/beginners/lse.html",
        "author": "Rouxers",
        "license": "Referência factual; explicação e estados próprios do Nexus Cube"
      }
    ]
  },
  {
    "id": "roux/lse/eo-quatro",
    "kind": "exercise",
    "family": "LSE",
    "methodId": "roux",
    "stageId": "lse",
    "groupId": "eo",
    "group": "Orientação de arestas",
    "name": "EO com quatro arestas ruins",
    "aliases": [
      "eo-quatro",
      "últimas seis arestas"
    ],
    "nameKind": "descriptive",
    "nameSource": "Títulos didáticos autorais Nexus Cube; não são nomes universais de casos.",
    "setup": "U M U2 M' U' M U2 M' U M U' M'",
    "solution": "M U M' U'",
    "alternatives": [],
    "objective": "Identifique as quatro arestas ruins e observe como M leva duas posições para a camada superior. U muda a seleção antes de restaurar M.",
    "preconditions": [
      "Dois blocos e todos os cantos resolvidos na referência fixa.",
      "Peças já corretas que devem voltar corretas ao final: DL, FL, BL, DFL, DBL, DR, FR, BR, DFR, DBR, UFR, URB, UBL, ULF."
    ],
    "preservation": [
      "Ao concluir, preserve DL, FL, BL, DFL, DBL, DR, FR, BR, DFR, DBR, UFR, URB, UBL, ULF.",
      "Alguns movimentos podem deslocar temporariamente peças protegidas; confira sua restauração no fim."
    ],
    "milestones": [
      {
        "step": 0,
        "title": "Reconhecer e planejar",
        "explanation": "Identifique as quatro arestas ruins e observe como M leva duas posições para a camada superior. U muda a seleção antes de restaurar M. Estado inicial: UF em UL (girado); UR em UR (girado); UB em UB (girado); UL em DB (girado); DF em DF (correto); DB em UF."
      },
      {
        "step": 4,
        "title": "EO concluída",
        "explanation": "O U final realinha os cantos aos blocos. Confira as seis arestas orientadas antes de tratar UL/UR. Confira: UF em DB; UR em UL; UB em UF; UL em UB; DF em DF (correto); DB em UR."
      }
    ],
    "focus": {
      "kind": "pieces",
      "pieces": [
        "UF",
        "UR",
        "UB",
        "UL",
        "DF",
        "DB"
      ],
      "referencePieces": [
        "DL",
        "FL",
        "BL",
        "DFL",
        "DBL",
        "DR",
        "FR",
        "BR",
        "DFR",
        "DBR",
        "UFR",
        "URB",
        "UBL",
        "ULF",
        "U",
        "D"
      ]
    },
    "validation": {
      "goal": "lse-eo",
      "preserve": [
        "DL",
        "FL",
        "BL",
        "DFL",
        "DBL",
        "DR",
        "FR",
        "BR",
        "DFR",
        "DBR",
        "UFR",
        "URB",
        "UBL",
        "ULF"
      ],
      "referenceFrame": "fixed"
    },
    "provenance": [
      {
        "title": "Corpus didático Nexus Cube",
        "url": "docs/expansion-curation/README.md",
        "author": "Nexus Cube, curadoria Trama",
        "license": "Produção autoral do projeto",
        "notes": "Estados e sequências montados localmente e verificados com KPuzzle e modelo geométrico. Exemplos finitos, não catálogo universal de construções intuitivas."
      },
      {
        "title": "Últimas seis arestas, método original",
        "url": "http://grrroux.free.fr/method/Step_4.html",
        "author": "Gilles Roux",
        "license": "Referência factual; sem cópia de exemplos ou assets"
      },
      {
        "title": "LSE, referência vertical e progressão",
        "url": "https://tutorial.rouxers.com/beginners/lse.html",
        "author": "Rouxers",
        "license": "Referência factual; explicação e estados próprios do Nexus Cube"
      }
    ]
  },
  {
    "id": "roux/lse/eo-seis",
    "kind": "exercise",
    "family": "LSE",
    "methodId": "roux",
    "stageId": "lse",
    "groupId": "eo",
    "group": "Orientação de arestas",
    "name": "EO com seis arestas ruins",
    "aliases": [
      "eo-seis",
      "últimas seis arestas"
    ],
    "nameKind": "descriptive",
    "nameSource": "Títulos didáticos autorais Nexus Cube; não são nomes universais de casos.",
    "setup": "U M U2 M' U' M U2 M' M U' M' U2 M U M U M' U' M' U2",
    "solution": "U2 M U M U' M' U' M' U2 M U M'",
    "alternatives": [],
    "objective": "As seis arestas estão ruins com os centros de referência já no eixo vertical. Siga este exemplo guiado por M/U e reconte nos marcos; não confunda orientação com posição final.",
    "preconditions": [
      "Dois blocos e todos os cantos resolvidos na referência fixa.",
      "Peças já corretas que devem voltar corretas ao final: DL, FL, BL, DFL, DBL, DR, FR, BR, DFR, DBR, UFR, URB, UBL, ULF."
    ],
    "preservation": [
      "Ao concluir, preserve DL, FL, BL, DFL, DBL, DR, FR, BR, DFR, DBR, UFR, URB, UBL, ULF.",
      "Alguns movimentos podem deslocar temporariamente peças protegidas; confira sua restauração no fim."
    ],
    "milestones": [
      {
        "step": 0,
        "title": "Reconhecer e planejar",
        "explanation": "As seis arestas estão ruins com os centros de referência já no eixo vertical. Siga este exemplo guiado por M/U e reconte nos marcos; não confunda orientação com posição final. Estado inicial: UF em UL (girado); UR em UB (girado); UB em DF (girado); UL em UF (girado); DF em DB (girado); DB em UR (girado)."
      },
      {
        "step": 4,
        "title": "Primeira transformação",
        "explanation": "A distribuição muda. Observe os adesivos brancos/amarelos nas seis identidades, inclusive DF e DB. Confira: UF em DF; UR em DB (girado); UB em UB (girado); UL em UL (correto); DF em UR; DB em UF."
      },
      {
        "step": 8,
        "title": "Preparar a conclusão",
        "explanation": "M também movimenta centros; mantenha a referência inicial e confira novamente quando o eixo vertical estiver restaurado. Confira: UF em UR (girado); UR em UF (girado); UB em UB (correto); UL em UL (girado); DF em DF (correto); DB em DB (girado)."
      },
      {
        "step": 12,
        "title": "Seis arestas orientadas",
        "explanation": "EO termina com centros U/D no eixo vertical e cantos alinhados. Prossiga para UL/UR. Confira: UF em DB; UR em UL; UB em UF; UL em UB; DF em DF (correto); DB em UR."
      }
    ],
    "focus": {
      "kind": "pieces",
      "pieces": [
        "UF",
        "UR",
        "UB",
        "UL",
        "DF",
        "DB"
      ],
      "referencePieces": [
        "DL",
        "FL",
        "BL",
        "DFL",
        "DBL",
        "DR",
        "FR",
        "BR",
        "DFR",
        "DBR",
        "UFR",
        "URB",
        "UBL",
        "ULF",
        "U",
        "D"
      ]
    },
    "validation": {
      "goal": "lse-eo",
      "preserve": [
        "DL",
        "FL",
        "BL",
        "DFL",
        "DBL",
        "DR",
        "FR",
        "BR",
        "DFR",
        "DBR",
        "UFR",
        "URB",
        "UBL",
        "ULF"
      ],
      "referenceFrame": "fixed"
    },
    "provenance": [
      {
        "title": "Corpus didático Nexus Cube",
        "url": "docs/expansion-curation/README.md",
        "author": "Nexus Cube, curadoria Trama",
        "license": "Produção autoral do projeto",
        "notes": "Estados e sequências montados localmente e verificados com KPuzzle e modelo geométrico. Exemplos finitos, não catálogo universal de construções intuitivas."
      },
      {
        "title": "Últimas seis arestas, método original",
        "url": "http://grrroux.free.fr/method/Step_4.html",
        "author": "Gilles Roux",
        "license": "Referência factual; sem cópia de exemplos ou assets"
      },
      {
        "title": "LSE, referência vertical e progressão",
        "url": "https://tutorial.rouxers.com/beginners/lse.html",
        "author": "Rouxers",
        "license": "Referência factual; explicação e estados próprios do Nexus Cube"
      }
    ]
  },
  {
    "id": "roux/lse/ul-ur-trocas",
    "kind": "exercise",
    "family": "LSE",
    "methodId": "roux",
    "stageId": "lse",
    "groupId": "ul-ur",
    "group": "Arestas esquerda e direita",
    "name": "Posicionar UL e UR por trocas",
    "aliases": [
      "ul-ur-trocas",
      "últimas seis arestas"
    ],
    "nameKind": "descriptive",
    "nameSource": "Títulos didáticos autorais Nexus Cube; não são nomes universais de casos.",
    "setup": "U2 M2 U2 M2 U M U2 M' U' M U2 M'",
    "solution": "M U2 M' U M U2 M' U'",
    "alternatives": [],
    "objective": "EO já está pronta. Rastreie amarelo/laranja (UL) e amarelo/vermelho (UR). As trocas M U2 M' deslocam arestas entre U e D; os ajustes U alinham sua chegada.",
    "preconditions": [
      "Dois blocos e todos os cantos resolvidos na referência fixa.",
      "EO concluída: centros U/D e adesivos U/D das seis arestas no eixo vertical.",
      "Peças já corretas que devem voltar corretas ao final: DL, FL, BL, DFL, DBL, DR, FR, BR, DFR, DBR, UFR, URB, UBL, ULF."
    ],
    "preservation": [
      "Ao concluir, preserve DL, FL, BL, DFL, DBL, DR, FR, BR, DFR, DBR, UFR, URB, UBL, ULF.",
      "Alguns movimentos podem deslocar temporariamente peças protegidas; confira sua restauração no fim."
    ],
    "milestones": [
      {
        "step": 0,
        "title": "Reconhecer e planejar",
        "explanation": "EO já está pronta. Rastreie amarelo/laranja (UL) e amarelo/vermelho (UR). As trocas M U2 M' deslocam arestas entre U e D; os ajustes U alinham sua chegada. Estado inicial: UL em UB; UR em UL."
      },
      {
        "step": 3,
        "title": "Primeira troca",
        "explanation": "Observe qual aresta alvo mudou de camada e qual ocupou sua antiga posição. Confira: UL em DB; UR em UR (correto)."
      },
      {
        "step": 4,
        "title": "Alinhar a próxima troca",
        "explanation": "U reposiciona os cantos e as arestas superiores em conjunto. Confira: UL em DB; UR em UF."
      },
      {
        "step": 7,
        "title": "Segunda troca",
        "explanation": "M retorna à referência anterior; acompanhe ambas as identidades alvo. Confira: UL em UB; UR em UF."
      },
      {
        "step": 8,
        "title": "UL/UR concluídas",
        "explanation": "O ajuste final realinha os cantos. UL e UR estão corretas, deixando quatro arestas em M para terminar. Confira: UL em UL (correto); UR em UR (correto)."
      }
    ],
    "focus": {
      "kind": "pieces",
      "pieces": [
        "UL",
        "UR"
      ],
      "referencePieces": [
        "DL",
        "FL",
        "BL",
        "DFL",
        "DBL",
        "DR",
        "FR",
        "BR",
        "DFR",
        "DBR",
        "UFR",
        "URB",
        "UBL",
        "ULF",
        "U",
        "D"
      ]
    },
    "validation": {
      "goal": "lse-lr",
      "preserve": [
        "DL",
        "FL",
        "BL",
        "DFL",
        "DBL",
        "DR",
        "FR",
        "BR",
        "DFR",
        "DBR",
        "UFR",
        "URB",
        "UBL",
        "ULF"
      ],
      "referenceFrame": "fixed"
    },
    "provenance": [
      {
        "title": "Corpus didático Nexus Cube",
        "url": "docs/expansion-curation/README.md",
        "author": "Nexus Cube, curadoria Trama",
        "license": "Produção autoral do projeto",
        "notes": "Estados e sequências montados localmente e verificados com KPuzzle e modelo geométrico. Exemplos finitos, não catálogo universal de construções intuitivas."
      },
      {
        "title": "Últimas seis arestas, método original",
        "url": "http://grrroux.free.fr/method/Step_4.html",
        "author": "Gilles Roux",
        "license": "Referência factual; sem cópia de exemplos ou assets"
      },
      {
        "title": "LSE, referência vertical e progressão",
        "url": "https://tutorial.rouxers.com/beginners/lse.html",
        "author": "Rouxers",
        "license": "Referência factual; explicação e estados próprios do Nexus Cube"
      }
    ]
  },
  {
    "id": "roux/lse/ul-ur-meias-voltas",
    "kind": "exercise",
    "family": "LSE",
    "methodId": "roux",
    "stageId": "lse",
    "groupId": "ul-ur",
    "group": "Arestas esquerda e direita",
    "name": "Posicionar UL e UR com M2",
    "aliases": [
      "ul-ur-meias-voltas",
      "últimas seis arestas"
    ],
    "nameKind": "descriptive",
    "nameSource": "Títulos didáticos autorais Nexus Cube; não são nomes universais de casos.",
    "setup": "U2 M2 U2 M2 U M2 U' M2 U M2 U' M2",
    "solution": "M2 U M2 U' M2 U M2 U'",
    "alternatives": [],
    "objective": "Use meias voltas de M para transportar arestas entre frente e fundo, mantendo EO. Acompanhe UL e UR por identidade, mesmo quando passam por D.",
    "preconditions": [
      "Dois blocos e todos os cantos resolvidos na referência fixa.",
      "EO concluída: centros U/D e adesivos U/D das seis arestas no eixo vertical.",
      "Peças já corretas que devem voltar corretas ao final: DL, FL, BL, DFL, DBL, DR, FR, BR, DFR, DBR, UFR, URB, UBL, ULF."
    ],
    "preservation": [
      "Ao concluir, preserve DL, FL, BL, DFL, DBL, DR, FR, BR, DFR, DBR, UFR, URB, UBL, ULF.",
      "Alguns movimentos podem deslocar temporariamente peças protegidas; confira sua restauração no fim."
    ],
    "milestones": [
      {
        "step": 0,
        "title": "Reconhecer e planejar",
        "explanation": "Use meias voltas de M para transportar arestas entre frente e fundo, mantendo EO. Acompanhe UL e UR por identidade, mesmo quando passam por D. Estado inicial: UL em DF; UR em DB."
      },
      {
        "step": 4,
        "title": "Transportar as duas arestas",
        "explanation": "As peças alvo mudam de posição enquanto os blocos permanecem protegidos. Confira: UL em UB; UR em UF."
      },
      {
        "step": 8,
        "title": "UL/UR alinhadas",
        "explanation": "Confira as arestas laterais junto aos respectivos cantos. A camada M ainda precisa ser concluída. Confira: UL em UL (correto); UR em UR (correto)."
      }
    ],
    "focus": {
      "kind": "pieces",
      "pieces": [
        "UL",
        "UR"
      ],
      "referencePieces": [
        "DL",
        "FL",
        "BL",
        "DFL",
        "DBL",
        "DR",
        "FR",
        "BR",
        "DFR",
        "DBR",
        "UFR",
        "URB",
        "UBL",
        "ULF",
        "U",
        "D"
      ]
    },
    "validation": {
      "goal": "lse-lr",
      "preserve": [
        "DL",
        "FL",
        "BL",
        "DFL",
        "DBL",
        "DR",
        "FR",
        "BR",
        "DFR",
        "DBR",
        "UFR",
        "URB",
        "UBL",
        "ULF"
      ],
      "referenceFrame": "fixed"
    },
    "provenance": [
      {
        "title": "Corpus didático Nexus Cube",
        "url": "docs/expansion-curation/README.md",
        "author": "Nexus Cube, curadoria Trama",
        "license": "Produção autoral do projeto",
        "notes": "Estados e sequências montados localmente e verificados com KPuzzle e modelo geométrico. Exemplos finitos, não catálogo universal de construções intuitivas."
      },
      {
        "title": "Últimas seis arestas, método original",
        "url": "http://grrroux.free.fr/method/Step_4.html",
        "author": "Gilles Roux",
        "license": "Referência factual; sem cópia de exemplos ou assets"
      },
      {
        "title": "LSE, referência vertical e progressão",
        "url": "https://tutorial.rouxers.com/beginners/lse.html",
        "author": "Rouxers",
        "license": "Referência factual; explicação e estados próprios do Nexus Cube"
      }
    ]
  },
  {
    "id": "roux/lse/quatro-arestas",
    "kind": "exercise",
    "family": "LSE",
    "methodId": "roux",
    "stageId": "lse",
    "groupId": "finish",
    "group": "Conclusão",
    "name": "Concluir as quatro arestas de M",
    "aliases": [
      "quatro-arestas",
      "últimas seis arestas"
    ],
    "nameKind": "descriptive",
    "nameSource": "Títulos didáticos autorais Nexus Cube; não são nomes universais de casos.",
    "setup": "U2 M2 U2 M2",
    "solution": "M2 U2 M2 U2",
    "alternatives": [],
    "objective": "Cantos, blocos, EO e UL/UR já estão corretos. Restam duas trocas de arestas em M neste exemplo. Siga também os centros até retornarem às faces originais.",
    "preconditions": [
      "Dois blocos e todos os cantos resolvidos na referência fixa.",
      "EO concluída: centros U/D e adesivos U/D das seis arestas no eixo vertical.",
      "Peças já corretas que devem voltar corretas ao final: DL, FL, BL, DFL, DBL, DR, FR, BR, DFR, DBR, UFR, URB, UBL, ULF."
    ],
    "preservation": [
      "Ao concluir, preserve DL, FL, BL, DFL, DBL, DR, FR, BR, DFR, DBR, UFR, URB, UBL, ULF.",
      "Alguns movimentos podem deslocar temporariamente peças protegidas; confira sua restauração no fim."
    ],
    "milestones": [
      {
        "step": 0,
        "title": "Reconhecer e planejar",
        "explanation": "Cantos, blocos, EO e UL/UR já estão corretos. Restam duas trocas de arestas em M neste exemplo. Siga também os centros até retornarem às faces originais. Estado inicial: UF em UB; UB em UF; DF em DB; DB em DF; U em U (correto); D em D (correto); F em F (correto); B em B (correto)."
      },
      {
        "step": 2,
        "title": "Transportar em M",
        "explanation": "Os centros mudam com M2; U2 reposiciona o par superior temporariamente. Confira: UF em DF; UB em DB; DF em UB; DB em UF; U em D; D em U; F em B; B em F."
      },
      {
        "step": 4,
        "title": "Cubo resolvido",
        "explanation": "Confira todas as arestas e os seis centros. O último U2 também restaura os cantos e UL/UR. Confira: UF em UF (correto); UB em UB (correto); DF em DF (correto); DB em DB (correto); U em U (correto); D em D (correto); F em F (correto); B em B (correto)."
      }
    ],
    "focus": {
      "kind": "pieces",
      "pieces": [
        "UF",
        "UB",
        "DF",
        "DB",
        "U",
        "D",
        "F",
        "B"
      ],
      "referencePieces": [
        "DL",
        "FL",
        "BL",
        "DFL",
        "DBL",
        "DR",
        "FR",
        "BR",
        "DFR",
        "DBR",
        "UFR",
        "URB",
        "UBL",
        "ULF",
        "U",
        "D"
      ]
    },
    "validation": {
      "goal": "solved",
      "preserve": [
        "DL",
        "FL",
        "BL",
        "DFL",
        "DBL",
        "DR",
        "FR",
        "BR",
        "DFR",
        "DBR",
        "UFR",
        "URB",
        "UBL",
        "ULF"
      ],
      "referenceFrame": "fixed"
    },
    "provenance": [
      {
        "title": "Corpus didático Nexus Cube",
        "url": "docs/expansion-curation/README.md",
        "author": "Nexus Cube, curadoria Trama",
        "license": "Produção autoral do projeto",
        "notes": "Estados e sequências montados localmente e verificados com KPuzzle e modelo geométrico. Exemplos finitos, não catálogo universal de construções intuitivas."
      },
      {
        "title": "Últimas seis arestas, método original",
        "url": "http://grrroux.free.fr/method/Step_4.html",
        "author": "Gilles Roux",
        "license": "Referência factual; sem cópia de exemplos ou assets"
      },
      {
        "title": "LSE, referência vertical e progressão",
        "url": "https://tutorial.rouxers.com/beginners/lse.html",
        "author": "Rouxers",
        "license": "Referência factual; explicação e estados próprios do Nexus Cube"
      }
    ]
  },
  {
    "id": "roux/lse/fechar-centros",
    "kind": "exercise",
    "family": "LSE",
    "methodId": "roux",
    "stageId": "lse",
    "groupId": "finish",
    "group": "Conclusão",
    "name": "Finalizar arestas e centros juntos",
    "aliases": [
      "fechar-centros",
      "últimas seis arestas"
    ],
    "nameKind": "descriptive",
    "nameSource": "Títulos didáticos autorais Nexus Cube; não são nomes universais de casos.",
    "setup": "M2",
    "solution": "M2",
    "alternatives": [],
    "objective": "EO e UL/UR estão prontas, mas os centros U/D e F/B estão trocados entre faces opostas. As quatro arestas de M acompanham os centros; uma meia volta final resolve ambos.",
    "preconditions": [
      "Dois blocos e todos os cantos resolvidos na referência fixa.",
      "EO concluída: centros U/D e adesivos U/D das seis arestas no eixo vertical.",
      "Peças já corretas que devem voltar corretas ao final: DL, FL, BL, DFL, DBL, DR, FR, BR, DFR, DBR, UFR, URB, UBL, ULF."
    ],
    "preservation": [
      "Ao concluir, preserve DL, FL, BL, DFL, DBL, DR, FR, BR, DFR, DBR, UFR, URB, UBL, ULF.",
      "Alguns movimentos podem deslocar temporariamente peças protegidas; confira sua restauração no fim."
    ],
    "milestones": [
      {
        "step": 0,
        "title": "Reconhecer e planejar",
        "explanation": "EO e UL/UR estão prontas, mas os centros U/D e F/B estão trocados entre faces opostas. As quatro arestas de M acompanham os centros; uma meia volta final resolve ambos. Estado inicial: UF em DB; UR em UR (correto); UB em DF; UL em UL (correto); DF em UB; DB em UF; U em D; D em U; F em B; B em F."
      },
      {
        "step": 1,
        "title": "Resolução concluída",
        "explanation": "Todas as peças concordam com os centros originais. Centros corretos são parte da conclusão de LSE. Confira: UF em UF (correto); UR em UR (correto); UB em UB (correto); UL em UL (correto); DF em DF (correto); DB em DB (correto); U em U (correto); D em D (correto); F em F (correto); B em B (correto)."
      }
    ],
    "focus": {
      "kind": "pieces",
      "pieces": [
        "UF",
        "UR",
        "UB",
        "UL",
        "DF",
        "DB",
        "U",
        "D",
        "F",
        "B"
      ],
      "referencePieces": [
        "DL",
        "FL",
        "BL",
        "DFL",
        "DBL",
        "DR",
        "FR",
        "BR",
        "DFR",
        "DBR",
        "UFR",
        "URB",
        "UBL",
        "ULF",
        "U",
        "D"
      ]
    },
    "validation": {
      "goal": "solved",
      "preserve": [
        "DL",
        "FL",
        "BL",
        "DFL",
        "DBL",
        "DR",
        "FR",
        "BR",
        "DFR",
        "DBR",
        "UFR",
        "URB",
        "UBL",
        "ULF"
      ],
      "referenceFrame": "fixed"
    },
    "provenance": [
      {
        "title": "Corpus didático Nexus Cube",
        "url": "docs/expansion-curation/README.md",
        "author": "Nexus Cube, curadoria Trama",
        "license": "Produção autoral do projeto",
        "notes": "Estados e sequências montados localmente e verificados com KPuzzle e modelo geométrico. Exemplos finitos, não catálogo universal de construções intuitivas."
      },
      {
        "title": "Últimas seis arestas, método original",
        "url": "http://grrroux.free.fr/method/Step_4.html",
        "author": "Gilles Roux",
        "license": "Referência factual; sem cópia de exemplos ou assets"
      },
      {
        "title": "LSE, referência vertical e progressão",
        "url": "https://tutorial.rouxers.com/beginners/lse.html",
        "author": "Rouxers",
        "license": "Referência factual; explicação e estados próprios do Nexus Cube"
      }
    ]
  }
];
