import test from 'node:test';
import assert from 'node:assert/strict';
import { createSyncEngine } from '../../src/cloud/sync-engine';
import { createMemoryCloudStore, initialCloudState } from '../../src/cloud/storage';
import { fixtureBase, fixturePage, oracleWire, emptyPage } from '../security/sync-oracle';
import { automaticSyncFixture, SYNC_OPERATION_IDS } from '../security/sync-fixtures';
import { QA_IDENTITIES } from '../security/fixtures';
import type { ContextHandle } from '../../src/cloud/types';
import type { SyncOperation } from '../../src/cloud/sync-types';

test('A1 confirmed commit propagates to separate A2 store and preserves local selection, B and guest', async () => {
  const fixture = automaticSyncFixture(); let saved: { operation: SyncOperation; page: ReturnType<typeof fixturePage> } | undefined; let applications = 0; let serverRevision = '9';
  const base = fixtureBase(fixture.a1, '9');
  const sync = (outbox: any[]) => ({ version: 1 as const, revision: '9', epoch: 'synthetic-epoch', base: structuredClone(base), outbox, reconciliation: false, status: 'pending' as const, error: null, received: null, adoptedSources: {}, hydrated: true });
  const stateA1 = initialCloudState(); stateA1.gate = 'active'; stateA1.generation = 7; stateA1.user = { ...QA_IDENTITIES.a }; stateA1.accounts[QA_IDENTITIES.a.id] = { data: structuredClone(fixture.afterCreateA1), revision: 1, sync: sync([{ id: SYNC_OPERATION_IDS.create, changes: [{ entity: 'solve', id: fixture.newSolve.id, before: null, after: { entity: 'solve', id: fixture.newSolve.id, value: fixture.newSolve, listPosition: '1' } }] }]) };
  const a2 = structuredClone(fixture.a2); const stateA2 = initialCloudState(); stateA2.gate = 'active'; stateA2.generation = 7; stateA2.user = { ...QA_IDENTITIES.a }; stateA2.accounts[QA_IDENTITIES.a.id] = { data: a2, revision: 1, sync: sync([]) }; stateA2.accounts[QA_IDENTITIES.b.id] = { data: structuredClone(fixture.b), revision: 1 }; stateA2.guest = { data: structuredClone(fixture.guest), revision: 1 };
  const context: ContextHandle = { projectRef: 'qa-a1-a2', userId: QA_IDENTITIES.a.id, generation: 7 };
  const transport = async () => ({ status: async () => ({ revision: serverRevision }), lookupSource: async () => ({ operationId: null }), pull: async ({ afterRevision }: { afterRevision: string }) => afterRevision === '9' ? (saved ? saved.page : emptyPage('9')) : emptyPage('10'), push: async (operation: SyncOperation) => { assert.equal(operation.baseRevision, '9'); assert.equal(operation.changes.length, 1); if (saved) { assert.deepEqual(operation, saved.operation); return { kind: 'applied' as const, operationId: operation.operationId, requestDigest: operation.requestDigest, commitRevision: '10', changeCount: 1 }; } applications++; saved = { operation: structuredClone(operation), page: fixturePage(operation.changes.map(change => ({ entity: change.entity, id: change.id, revision: '10', tombstone: change.action === 'delete', record: change.record })), { operationId: operation.operationId, requestDigest: operation.requestDigest }, '10', '9') }; serverRevision = '10'; return { kind: 'applied' as const, operationId: operation.operationId, requestDigest: operation.requestDigest, commitRevision: '10', changeCount: 1 }; } });
  const make = (seed: typeof stateA1) => { const store = createMemoryCloudStore(seed); const engine = createSyncEngine({ store, context: () => context, isCurrent: c => c.userId === QA_IDENTITIES.a.id && c.generation === 7, guard: (root, c) => { if (root.user?.id !== c.userId || root.generation !== c.generation) throw new Error('context'); }, transport, online: () => true }); return { store, engine }; };
  const one = make(stateA1); await one.engine.drain(); assert.equal(applications, 1); const afterA1 = await one.store.read(); assert.equal(afterA1.accounts[QA_IDENTITIES.a.id].sync?.revision, '10'); assert.equal(afterA1.accounts[QA_IDENTITIES.a.id].sync?.outbox.length, 0); assert.equal(afterA1.accounts[QA_IDENTITIES.a.id].sync?.status, 'synced');
  const two = make(stateA2); await two.engine.drain(); const afterA2 = await two.store.read(); assert.deepEqual(afterA2.accounts[QA_IDENTITIES.a.id].data, fixture.afterCreateA2); assert.equal(afterA2.accounts[QA_IDENTITIES.a.id].data.activeSessionId, 'other-session-id'); assert.equal(afterA2.accounts[QA_IDENTITIES.a.id].sync?.revision, '10'); assert.equal(afterA2.accounts[QA_IDENTITIES.a.id].sync?.outbox.length, 0); assert.deepEqual(afterA2.accounts[QA_IDENTITIES.b.id].data, fixture.b); assert.deepEqual(afterA2.guest?.data, fixture.guest); assert.equal(applications, 1); one.engine.dispose(); two.engine.dispose();
});
