// Generated by tests/domain/compile-catalog.ts from MIT Cube Coach data.
// See docs/sources-and-licenses.md. Do not edit by hand.
export const COMPILED_CASES = [
  {
    "id": "OLL-01",
    "family": "OLL",
    "name": "OLL 1",
    "group": "Ponto",
    "algorithm": "R U2 R' R' F R F' U2 R' F R F'",
    "alternatives": [],
    "setup": "F R' F' R U2 F R' F' R R U2 R'",
    "twoLook": true,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-02",
    "family": "OLL",
    "name": "OLL 2",
    "group": "Ponto",
    "algorithm": "r U r' U2 r U2 R' U2 R U' r'",
    "alternatives": [
      "y' F R U R' U' F' f R U R' U' f' y",
      "y' F R U R' U' S R U R' U' f' y"
    ],
    "setup": "r U R' U2 R U2 r' U2 r U' r'",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-03",
    "family": "OLL",
    "name": "OLL 3",
    "group": "Ponto",
    "algorithm": "r' R2 U R' U r U2 r' U M'",
    "alternatives": [
      "y F U R U' R' F' U F R U R' U' F' y'",
      "y' f R U R' U' f' U' F R U R' U' F' y"
    ],
    "setup": "M U' r U2 r' U' R U' R2 r",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-04",
    "family": "OLL",
    "name": "OLL 4",
    "group": "Ponto",
    "algorithm": "M U' r U2 r' U' R U' R' M'",
    "alternatives": [
      "y F U R U' R' F' U' F R U R' U' F' y'",
      "y' f R U R' U' f' U F R U R' U' F' y"
    ],
    "setup": "M R U R' U r U2 r' U M'",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-05",
    "family": "OLL",
    "name": "OLL 5",
    "group": "Quadrado",
    "algorithm": "l' U2 L U L' U l",
    "alternatives": [
      "y2 r' U2 R U R' U r y2"
    ],
    "setup": "l' U' L U' L' U2 l",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-06",
    "family": "OLL",
    "name": "OLL 6",
    "group": "Quadrado",
    "algorithm": "r U2 R' U' R U' r'",
    "alternatives": [],
    "setup": "r U R' U R U2 r'",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-07",
    "family": "OLL",
    "name": "OLL 7",
    "group": "Raio pequeno",
    "algorithm": "r U R' U R U2 r'",
    "alternatives": [],
    "setup": "r U2 R' U' R U' r'",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-08",
    "family": "OLL",
    "name": "OLL 8",
    "group": "Raio pequeno",
    "algorithm": "l' U' L U' L' U2 l",
    "alternatives": [
      "R U2 R' U2 R' F R F'",
      "y2 r' U' R U' R' U2 r y2"
    ],
    "setup": "l' U2 L U L' U l",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-09",
    "family": "OLL",
    "name": "OLL 9",
    "group": "Peixe",
    "algorithm": "R U R' U' R' F R2 U R' U' F'",
    "alternatives": [],
    "setup": "F U R U' R2 F' R U R U' R'",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-10",
    "family": "OLL",
    "name": "OLL 10",
    "group": "Peixe",
    "algorithm": "R U R' U R' F R F' R U2 R'",
    "alternatives": [
      "y2 r U R' U R U' R' U' r' R U R U' R' y2"
    ],
    "setup": "R U2 R' F R' F' R U' R U' R'",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-11",
    "family": "OLL",
    "name": "OLL 11",
    "group": "Raio pequeno",
    "algorithm": "r U R' U R' F R F' R U2 r'",
    "alternatives": [
      "y2 r' R2 U R' U R U2 R' U M' y2"
    ],
    "setup": "r U2 R' F R' F' R U' R U' r'",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-12",
    "family": "OLL",
    "name": "OLL 12",
    "group": "Raio pequeno",
    "algorithm": "M' R' U' R U' R' U2 R U' R r'",
    "alternatives": [],
    "setup": "r R' U R' U2 R U R' U R M",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-13",
    "family": "OLL",
    "name": "OLL 13",
    "group": "Cavalo",
    "algorithm": "F U R U' R2 F' R U R U' R'",
    "alternatives": [
      "r U' r' U' r U r' y' R' U R y"
    ],
    "setup": "R U R' U' R' F R2 U R' U' F'",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-14",
    "family": "OLL",
    "name": "OLL 14",
    "group": "Cavalo",
    "algorithm": "R' F R U R' F' R F U' F'",
    "alternatives": [],
    "setup": "F U F' R' F R U' R' F' R",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-15",
    "family": "OLL",
    "name": "OLL 15",
    "group": "Cavalo",
    "algorithm": "l' U' l L' U' L U l' U l",
    "alternatives": [
      "y2 r' U' r R' U' R U r' U r y2"
    ],
    "setup": "l' U' l U' L' U L l' U l",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-16",
    "family": "OLL",
    "name": "OLL 16",
    "group": "Cavalo",
    "algorithm": "r U r' R U R' U' r U' r'",
    "alternatives": [],
    "setup": "r U r' U R U' R' r U' r'",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-17",
    "family": "OLL",
    "name": "OLL 17",
    "group": "Ponto",
    "algorithm": "F R' F' R2 r' U R U' R' U' M'",
    "alternatives": [
      "y2 R U R' U R' F R F' U2 R' F R F' y2"
    ],
    "setup": "M U R U R' U' r R2 F R F'",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-18",
    "family": "OLL",
    "name": "OLL 18",
    "group": "Ponto",
    "algorithm": "r U R' U R U2 r' r' U' R U' R' U2 r",
    "alternatives": [
      "y R U2 R' R' F R F' U2 M' U R U' r' y'"
    ],
    "setup": "r' U2 R U R' U r r U2 R' U' R U' r'",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-19",
    "family": "OLL",
    "name": "OLL 19",
    "group": "Ponto",
    "algorithm": "r' R U R U R' U' M' R' F R F'",
    "alternatives": [],
    "setup": "F R' F' R M U R U' R' U' R' r",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-20",
    "family": "OLL",
    "name": "OLL 20",
    "group": "Ponto",
    "algorithm": "r U R' U' M2 U R U' R' U' M'",
    "alternatives": [
      "r' R U R U R' U' M2 U R U' r'"
    ],
    "setup": "M U R U R' U' M2 U R U' r'",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-21",
    "family": "OLL",
    "name": "OLL 21",
    "group": "Cruz",
    "algorithm": "R U2 R' U' R U R' U' R U' R'",
    "alternatives": [
      "y R U R' U R U' R' U R U2 R' y'"
    ],
    "setup": "R U R' U R U' R' U R U2 R'",
    "twoLook": true,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-22",
    "family": "OLL",
    "name": "OLL 22",
    "group": "Cruz",
    "algorithm": "R U2 R2 U' R2 U' R2 U2 R",
    "alternatives": [],
    "setup": "R' U2 R2 U R2 U R2 U2 R'",
    "twoLook": true,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-23",
    "family": "OLL",
    "name": "OLL 23",
    "group": "Cruz",
    "algorithm": "R2 D' R U2 R' D R U2 R",
    "alternatives": [
      "y2 R2 D R' U2 R D' R' U2 R' y2"
    ],
    "setup": "R' U2 R' D' R U2 R' D R2",
    "twoLook": true,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-24",
    "family": "OLL",
    "name": "OLL 24",
    "group": "Cruz",
    "algorithm": "r U R' U' r' F R F'",
    "alternatives": [
      "y R U R D R' U' R D' R2 y'"
    ],
    "setup": "F R' F' r U R U' r'",
    "twoLook": true,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-25",
    "family": "OLL",
    "name": "OLL 25",
    "group": "Cruz",
    "algorithm": "F' r U R' U' r' F R",
    "alternatives": [
      "y' R' F R B' R' F' R B y"
    ],
    "setup": "R' F' r U R U' r' F",
    "twoLook": true,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-26",
    "family": "OLL",
    "name": "OLL 26",
    "group": "Cruz",
    "algorithm": "R U2 R' U' R U' R'",
    "alternatives": [
      "y' R' U' R U' R' U2 R y"
    ],
    "setup": "R U R' U R U2 R'",
    "twoLook": true,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-27",
    "family": "OLL",
    "name": "OLL 27",
    "group": "Cruz",
    "algorithm": "R U R' U R U2 R'",
    "alternatives": [
      "y' R' U2 R U R' U R y"
    ],
    "setup": "R U2 R' U' R U' R'",
    "twoLook": true,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-28",
    "family": "OLL",
    "name": "OLL 28",
    "group": "Cantos orientados",
    "algorithm": "r U R' U' r' R U R U' R'",
    "alternatives": [],
    "setup": "R U R' U' R' r U R U' r'",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-29",
    "family": "OLL",
    "name": "OLL 29",
    "group": "Irregulares",
    "algorithm": "R U R' U' R U' R' F' U' F R U R'",
    "alternatives": [],
    "setup": "R U' R' F' U F R U R' U R U' R'",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-30",
    "family": "OLL",
    "name": "OLL 30",
    "group": "Irregulares",
    "algorithm": "F R' F R2 U' R' U' R U R' F2",
    "alternatives": [
      "F U R U2 R' U' R U2 R' U' F'"
    ],
    "setup": "F2 R U' R' U R U R2 F' R F'",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-31",
    "family": "OLL",
    "name": "OLL 31",
    "group": "Forma P",
    "algorithm": "R' U' F U R U' R' F' R",
    "alternatives": [],
    "setup": "R' F R U R' U' F' U R",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-32",
    "family": "OLL",
    "name": "OLL 32",
    "group": "Forma P",
    "algorithm": "L U F' U' L' U L F L'",
    "alternatives": [],
    "setup": "L F' L' U' L U F U' L'",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-33",
    "family": "OLL",
    "name": "OLL 33",
    "group": "Forma T",
    "algorithm": "R U R' U' R' F R F'",
    "alternatives": [],
    "setup": "F R' F' R U R U' R'",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-34",
    "family": "OLL",
    "name": "OLL 34",
    "group": "Forma C",
    "algorithm": "R U R2 U' R' F R U R U' F'",
    "alternatives": [
      "R U R' U' B' R' F R F' B"
    ],
    "setup": "F U R' U' R' F' R U R2 U' R'",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-35",
    "family": "OLL",
    "name": "OLL 35",
    "group": "Peixe",
    "algorithm": "R U2 R' R' F R F' R U2 R'",
    "alternatives": [],
    "setup": "R U2 R' F R' F' R R U2 R'",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-36",
    "family": "OLL",
    "name": "OLL 36",
    "group": "Forma W",
    "algorithm": "L' U' L U' L' U L U L F' L' F",
    "alternatives": [
      "y2 R' U' R U' R' U R U R B' R' B y2"
    ],
    "setup": "F' L F L' U' L' U' L U L' U L",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-37",
    "family": "OLL",
    "name": "OLL 37",
    "group": "Peixe",
    "algorithm": "F R' F' R U R U' R'",
    "alternatives": [
      "F R U' R' U' R U R' F'"
    ],
    "setup": "R U R' U' R' F R F'",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-38",
    "family": "OLL",
    "name": "OLL 38",
    "group": "Forma W",
    "algorithm": "R U R' U R U' R' U' R' F R F'",
    "alternatives": [],
    "setup": "F R' F' R U R U R' U' R U' R'",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-39",
    "family": "OLL",
    "name": "OLL 39",
    "group": "Raio grande",
    "algorithm": "L F' L' U' L U F U' L'",
    "alternatives": [
      "y2 R B' R' U' R U B U' R' y2"
    ],
    "setup": "L U F' U' L' U L F L'",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-40",
    "family": "OLL",
    "name": "OLL 40",
    "group": "Raio grande",
    "algorithm": "R' F R U R' U' F' U R",
    "alternatives": [],
    "setup": "R' U' F U R U' R' F' R",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-41",
    "family": "OLL",
    "name": "OLL 41",
    "group": "Irregulares",
    "algorithm": "R U R' U R U2 R' F R U R' U' F'",
    "alternatives": [],
    "setup": "F U R U' R' F' R U2 R' U' R U' R'",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-42",
    "family": "OLL",
    "name": "OLL 42",
    "group": "Irregulares",
    "algorithm": "R' U' R U' R' U2 R F R U R' U' F'",
    "alternatives": [],
    "setup": "F U R U' R' F' R' U2 R U R' U R",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-43",
    "family": "OLL",
    "name": "OLL 43",
    "group": "Forma P",
    "algorithm": "F' U' L' U L F",
    "alternatives": [
      "R' U' F R' F' R U R"
    ],
    "setup": "F' L' U' L U F",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-44",
    "family": "OLL",
    "name": "OLL 44",
    "group": "Forma P",
    "algorithm": "F U R U' R' F'",
    "alternatives": [
      "y2 f R U R' U' f' y2"
    ],
    "setup": "F R U R' U' F'",
    "twoLook": true,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-45",
    "family": "OLL",
    "name": "OLL 45",
    "group": "Forma T",
    "algorithm": "F R U R' U' F'",
    "alternatives": [],
    "setup": "F U R U' R' F'",
    "twoLook": true,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-46",
    "family": "OLL",
    "name": "OLL 46",
    "group": "Forma C",
    "algorithm": "R' U' R' F R F' U R",
    "alternatives": [],
    "setup": "R' U' F R' F' R U R",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-47",
    "family": "OLL",
    "name": "OLL 47",
    "group": "L pequeno",
    "algorithm": "R' U' R' F R F' R' F R F' U R",
    "alternatives": [
      "F' L' U' L U L' U' L U F",
      "y' F U R U' R' F' R U R' U R U2 R' y"
    ],
    "setup": "R' U' F R' F' R F R' F' R U R",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-48",
    "family": "OLL",
    "name": "OLL 48",
    "group": "L pequeno",
    "algorithm": "F R U R' U' R U R' U' F'",
    "alternatives": [],
    "setup": "F U R U' R' U R U' R' F'",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-49",
    "family": "OLL",
    "name": "OLL 49",
    "group": "L pequeno",
    "algorithm": "r U' r2 U r2 U r2 U' r",
    "alternatives": [],
    "setup": "r' U r2 U' r2 U' r2 U r'",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-50",
    "family": "OLL",
    "name": "OLL 50",
    "group": "L pequeno",
    "algorithm": "r' U r2 U' r2 U' r2 U r'",
    "alternatives": [],
    "setup": "r U' r2 U r2 U r2 U' r",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-51",
    "family": "OLL",
    "name": "OLL 51",
    "group": "Linha",
    "algorithm": "F U R U' R' U R U' R' F'",
    "alternatives": [
      "y2 f R U R' U' R U R' U' f' y2"
    ],
    "setup": "F R U R' U' R U R' U' F'",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-52",
    "family": "OLL",
    "name": "OLL 52",
    "group": "Linha",
    "algorithm": "R U R' U R U' B U' B' R'",
    "alternatives": [
      "U2 R' F' U' F U' R U R' U R",
      "R U R' U R U' y R U' R' F' y'"
    ],
    "setup": "R B U B' U R' U' R U' R'",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-53",
    "family": "OLL",
    "name": "OLL 53",
    "group": "L pequeno",
    "algorithm": "l' U2 L U L' U' L U L' U l",
    "alternatives": [
      "y2 r' U2 R U R' U' R U R' U r y2",
      "y r' U' R U' R' U R U' R' U2 r y'"
    ],
    "setup": "l' U' L U' L' U L U' L' U2 l",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-54",
    "family": "OLL",
    "name": "OLL 54",
    "group": "L pequeno",
    "algorithm": "r U2 R' U' R U R' U' R U' r'",
    "alternatives": [
      "y r U R' U R U' R' U R U2 r' y'"
    ],
    "setup": "r U R' U R U' R' U R U2 r'",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-55",
    "family": "OLL",
    "name": "OLL 55",
    "group": "Linha",
    "algorithm": "R' F R U R U' R2 F' R2 U' R' U R U R'",
    "alternatives": [
      "y R U2 R2 U' R U' R' U2 F R F' y'"
    ],
    "setup": "R U' R' U' R U R2 F R2 U R' U' R' F' R",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-56",
    "family": "OLL",
    "name": "OLL 56",
    "group": "Linha",
    "algorithm": "r' U' r U' R' U R U' R' U R r' U r",
    "alternatives": [
      "r U r' U R U' R' U R U' R' r U' r'",
      "r U r' U R U' R' U R U' M' U' r'"
    ],
    "setup": "r' U' r R' U' R U R' U' R U r' U r",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "OLL-57",
    "family": "OLL",
    "name": "OLL 57",
    "group": "Cantos orientados",
    "algorithm": "R U R' U' M' U R U' r'",
    "alternatives": [],
    "setup": "r U R' U' M U R U' R'",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "PLL-H",
    "family": "PLL",
    "name": "PLL H",
    "group": "Somente arestas",
    "algorithm": "M2 U M2 U2 M2 U M2",
    "alternatives": [
      "M2 U' M2 U2 M2 U' M2"
    ],
    "setup": "M2 U' M2 U2 M2 U' M2",
    "twoLook": true,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "PLL-Z",
    "family": "PLL",
    "name": "PLL Z",
    "group": "Somente arestas",
    "algorithm": "M' U M2 U M2 U M' U2 M2",
    "alternatives": [
      "y M' U' M2 U' M2 U' M' U2 M2 y' U2",
      "y M2 U M2 U M' U2 M2 U2 M' y' U'",
      "M2 U' M2 U' M' U2 M2 U2 M' U'"
    ],
    "setup": "M2 U2 M U' M2 U' M2 U' M",
    "twoLook": true,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "PLL-Ua",
    "family": "PLL",
    "name": "PLL Ua",
    "group": "Somente arestas",
    "algorithm": "M2 U M U2 M' U M2",
    "alternatives": [
      "R U' R U R U R U' R' U' R2",
      "y2 R2 U' R' U' R U R U R U' R y2"
    ],
    "setup": "M2 U' M U2 M' U' M2",
    "twoLook": true,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "PLL-Ub",
    "family": "PLL",
    "name": "PLL Ub",
    "group": "Somente arestas",
    "algorithm": "M2 U' M U2 M' U' M2",
    "alternatives": [
      "R2 U R U R' U' R' U' R' U R'",
      "y2 R' U R' U' R' U' R' U R U R2 y2"
    ],
    "setup": "M2 U M U2 M' U M2",
    "twoLook": true,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "PLL-Aa",
    "family": "PLL",
    "name": "PLL Aa",
    "group": "Cantos adjacentes",
    "algorithm": "x L2 D2 L' U' L D2 L' U L' x'",
    "alternatives": [
      "y' x' L' U L' D2 L U' L' D2 L2 x y",
      "y x R' U R' D2 R U' R' D2 R2 x' y'",
      "y2 x' R2 D2 R' U' R D2 R' U R' x y2"
    ],
    "setup": "x L U' L D2 L' U L D2 L2 x'",
    "twoLook": true,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "PLL-Ab",
    "family": "PLL",
    "name": "PLL Ab",
    "group": "Cantos adjacentes",
    "algorithm": "x' L2 D2 L U L' D2 L U' L x",
    "alternatives": [
      "y x L U' L D2 L' U L D2 L2 x' y'",
      "y2 x R2 D2 R U R' D2 R U' R x z2",
      "y' x' R U' R D2 R' U R D2 R2 x y"
    ],
    "setup": "x' L' U L' D2 L U' L' D2 L2 x",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "PLL-E",
    "family": "PLL",
    "name": "PLL E",
    "group": "Cantos diagonais",
    "algorithm": "x' L' U L D' L' U' L D L' U' L D' L' U L D x",
    "alternatives": [
      "x' R U' R' D R U R' D' R U R' D R U' R' D' x"
    ],
    "setup": "x' D' L' U' L D L' U L D' L' U L D L' U' L x",
    "twoLook": true,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "PLL-F",
    "family": "PLL",
    "name": "PLL F",
    "group": "Cantos adjacentes",
    "algorithm": "R' U' F' R U R' U' R' F R2 U' R' U' R U R' U R",
    "alternatives": [],
    "setup": "R' U' R U' R' U R U R2 F' R U R U' R' F U R",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "PLL-Ja",
    "family": "PLL",
    "name": "PLL Ja",
    "group": "Cantos adjacentes",
    "algorithm": "x R2 F R F' R U2 r' U r U2 x'",
    "alternatives": [
      "y2 L' U' L F L' U' L U L F' L2 U L y2 U",
      "y' R' U L' U2 R U' R' U2 R L y U'"
    ],
    "setup": "x U2 r' U' r U2 R' F R' F' R2 x'",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "PLL-Jb",
    "family": "PLL",
    "name": "PLL Jb",
    "group": "Cantos adjacentes",
    "algorithm": "R U R' F' R U R' U' R' F R2 U' R'",
    "alternatives": [],
    "setup": "R U R2 F' R U R U' R' F R U' R'",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "PLL-Ra",
    "family": "PLL",
    "name": "PLL Ra",
    "group": "Cantos adjacentes",
    "algorithm": "R U' R' U' R U R D R' U' R D' R' U2 R'",
    "alternatives": [
      "R U R' F' R U2 R' U2 R' F R U R U2 R'",
      "y' L U2 L' U2 L F' L' U' L U L F L2 y U2"
    ],
    "setup": "R U2 R D R' U R D' R' U' R' U R U R'",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "PLL-Rb",
    "family": "PLL",
    "name": "PLL Rb",
    "group": "Cantos adjacentes",
    "algorithm": "R2 F R U R U' R' F' R U2 R' U2 R",
    "alternatives": [
      "y' R' U2 R U2 R' F R U R' U' R' F' R2 y U2",
      "U' R' U2 R' D' R U' R' D R U R U' R' U' R U'"
    ],
    "setup": "R' U2 R U2 R' F R U R' U' R' F' R2",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "PLL-T",
    "family": "PLL",
    "name": "PLL T",
    "group": "Cantos adjacentes",
    "algorithm": "R U R' U' R' F R2 U' R' U' R U R' F'",
    "alternatives": [],
    "setup": "F R U' R' U R U R2 F' R U R U' R'",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "PLL-Y",
    "family": "PLL",
    "name": "PLL Y",
    "group": "Cantos diagonais",
    "algorithm": "F R U' R' U' R U R' F' R U R' U' R' F R F'",
    "alternatives": [
      "F R' F R2 U' R' U' R U R' F' R U R' U' F'"
    ],
    "setup": "F R' F' R U R U' R' F R U' R' U R U R' F'",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "PLL-V",
    "family": "PLL",
    "name": "PLL V",
    "group": "Cantos diagonais",
    "algorithm": "R' U R' U' y R' F' R2 U' R' U R' F R F y'",
    "alternatives": [
      "R' U R' U' R D' R' D R' U D' R2 U' R2 D R2",
      "z D' R2 D R2 U R' D' R U' R U R' D R U' z'",
      "R U2 R' D R U' R U' R U R2 D R' U' R D2",
      "x' R' F R F' U R U2 R' U' R U' R' U2 R U R' U' x"
    ],
    "setup": "y F' R' F' R U' R U R2 F R y' U R U' R",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "PLL-Na",
    "family": "PLL",
    "name": "PLL Na",
    "group": "Cantos diagonais",
    "algorithm": "R U R' U R U R' F' R U R' U' R' F R2 U' R' U2 R U' R'",
    "alternatives": [
      "z U R' D R2 U' R D' U R' D R2 U' R D' z' U'"
    ],
    "setup": "R U R' U2 R U R2 F' R U R U' R' F R U' R' U' R U' R'",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "PLL-Nb",
    "family": "PLL",
    "name": "PLL Nb",
    "group": "Cantos diagonais",
    "algorithm": "R' U R U' R' F' U' F R U R' F R' F' R U' R",
    "alternatives": [
      "z D' R U' R2 D R' U D' R U' R2 D R' U z' U"
    ],
    "setup": "R' U R' F R F' R U' R' F' U F R U R' U' R",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "PLL-Ga",
    "family": "PLL",
    "name": "PLL Ga",
    "group": "Cantos adjacentes",
    "algorithm": "R2 U R' U R' U' R U' R2 U' D R' U R D'",
    "alternatives": [
      "R2 u R' U R' U' R u' R2 y' R' U R y U'"
    ],
    "setup": "D R' U' R D' U R2 U R' U R U' R U' R2",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "PLL-Gb",
    "family": "PLL",
    "name": "PLL Gb",
    "group": "Cantos adjacentes",
    "algorithm": "R' U' R U D' R2 U R' U R U' R U' R2 D",
    "alternatives": [
      "y F' U' F R2 u R' U R U' R u' R2 y' U"
    ],
    "setup": "D' R2 U R' U R' U' R U' R2 D U' R' U R",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "PLL-Gc",
    "family": "PLL",
    "name": "PLL Gc",
    "group": "Cantos adjacentes",
    "algorithm": "R2 U' R U' R U R' U R2 U D' R U' R' D",
    "alternatives": [
      "y2 R2 F2 R U2 R U2 R' F R U R' U' R' F R2 y2 U",
      "R2 u' R U' R U R' u R2 y R U' R' y' U"
    ],
    "setup": "D' R U R' D U' R2 U' R U' R' U R' U R2",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  },
  {
    "id": "PLL-Gd",
    "family": "PLL",
    "name": "PLL Gd",
    "group": "Cantos adjacentes",
    "algorithm": "R U R' U' D R2 U' R U' R' U R' U R2 D'",
    "alternatives": [
      "R U R' y' R2 u' R U' R' U R' u R2 y U'"
    ],
    "setup": "D R2 U' R U' R U R' U R2 D' U R U' R'",
    "twoLook": false,
    "source": "https://github.com/lukejacksonn/cube/blob/856b269c63715fbd164b90aee1de5f4725fd277a/src/algorithms.ts"
  }
] as const;
